// packages/skeleton-svelte/src/composed/avatar/anatomy/avatar-fallback.svelte
<script lang="ts">
	import { mergeProps } from '@zag-js/svelte';
	import { classesAvatar } from '@skeletonlabs/skeleton-common';
	import { AvatarRootContext } from '../modules/context.js';
	import type { AvatarFallbackProps } from '../modules/types.js';

	const rootContext = AvatarRootContext.consume();
	const props: AvatarFallbackProps = $props();
	const { element, children, ...restAttributes } = $derived(props);
	const attributes = $derived(
		mergeProps(
			rootContext.api.getFallbackProps(),
			{
				class: classesAvatar.fallback
			},
			restAttributes
		)
	);
</script>

{#if element}
	{@render element({ attributes })}
{:else}
	<span {...attributes}>
		{@render children?.()}
	</span>
{/if}

// packages/skeleton-react/src/composed/avatar/anatomy/avatar-fallback.tsx
import { useContext } from 'react';
import { mergeProps } from '@zag-js/react';
import { AvatarRootContext } from '../modules/context.js';
import type { AvatarFallbackProps } from '../modules/types.js';
import { classesAvatar } from '@skeletonlabs/skeleton-common';

export default function (props: AvatarFallbackProps) {
	const rootContext = useContext(AvatarRootContext);
	const { element, children, ...restAttributes } = props;
	const attributes = mergeProps(
		rootContext.api.getFallbackProps(),
		{
			className: classesAvatar.fallback
		},
		restAttributes
	);
	return element ? element({ attributes }) : <span {...attributes}>{children}</span>;
}
