// sites/skeleton.dev/src/components/examples/guides/cookbook/image-layouts/react/grid.tsx
export default function Grid() {
	return (
		<section className="grid grid-cols-2 gap-6 md:grid-cols-3">
			{/* Row */}
			<img className="w-48 h-48 bg-surface-500 rounded-container" src="https://picsum.photos/192/192?random=1" alt="" />
			<img className="w-48 h-48 bg-surface-500 rounded-container" src="https://picsum.photos/192/192?random=2" alt="" />
			<img className="w-48 h-48 bg-surface-500 rounded-container" src="https://picsum.photos/192/192?random=3" alt="" />
			{/* Row */}
			<img className="w-48 h-48 bg-surface-500 rounded-container" src="https://picsum.photos/192/192?random=4" alt="" />
			<img className="w-48 h-48 bg-surface-500 rounded-container" src="https://picsum.photos/192/192?random=5" alt="" />
			<img className="w-48 h-48 bg-surface-500 rounded-container" src="https://picsum.photos/192/192?random=6" alt="" />
			{/* Row */}
			<img className="w-48 h-48 bg-surface-500 rounded-container" src="https://picsum.photos/192/192?random=7" alt="" />
			<img className="w-48 h-48 bg-surface-500 rounded-container" src="https://picsum.photos/192/192?random=8" alt="" />
			<img className="w-48 h-48 bg-surface-500 rounded-container" src="https://picsum.photos/192/192?random=9" alt="" />
		</section>
	);
}

// sites/skeleton.dev/src/components/examples/guides/cookbook/image-layouts/svelte/grid.svelte
<section class="grid grid-cols-2 gap-6 md:grid-cols-3">
	<!-- Row -->
	<img class="w-48 h-48 bg-surface-500 rounded-container" src="https://picsum.photos/192/192?random=1" alt="" />
	<img class="w-48 h-48 bg-surface-500 rounded-container" src="https://picsum.photos/192/192?random=2" alt="" />
	<img class="w-48 h-48 bg-surface-500 rounded-container" src="https://picsum.photos/192/192?random=3" alt="" />
	<!-- Row -->
	<img class="w-48 h-48 bg-surface-500 rounded-container" src="https://picsum.photos/192/192?random=4" alt="" />
	<img class="w-48 h-48 bg-surface-500 rounded-container" src="https://picsum.photos/192/192?random=5" alt="" />
	<img class="w-48 h-48 bg-surface-500 rounded-container" src="https://picsum.photos/192/192?random=6" alt="" />
	<!-- Row -->
	<img class="w-48 h-48 bg-surface-500 rounded-container" src="https://picsum.photos/192/192?random=7" alt="" />
	<img class="w-48 h-48 bg-surface-500 rounded-container" src="https://picsum.photos/192/192?random=8" alt="" />
	<img class="w-48 h-48 bg-surface-500 rounded-container" src="https://picsum.photos/192/192?random=9" alt="" />
</section>
