// packages/skeleton-react/src/components/tags-input/anatomy/hidden-input.tsx
import { TagsInputRootContext } from '../modules/root-context';
import type { HTMLAttributes } from '@/internal/html-attributes';
import type { PropsWithElement } from '@/internal/props-with-element';
import { classesTagsInput } from '@skeletonlabs/skeleton-common';
import { mergeProps } from '@zag-js/react';
import { use } from 'react';

export interface TagsInputHiddenInputProps extends PropsWithElement<'input'>, HTMLAttributes<'input', 'children'> {}

export default function HiddenInput(props: TagsInputHiddenInputProps) {
	const tagsInput = use(TagsInputRootContext);

	const { element, ...rest } = props;

	const attributes = mergeProps(
		tagsInput.getHiddenInputProps(),
		{
			className: classesTagsInput.hiddenInput,
		},
		rest,
	);

	return element ? element(attributes) : <input {...attributes} />;
}

// packages/skeleton-svelte/src/components/tags-input/anatomy/hidden-input.svelte
<script lang="ts" module>
	import type { HTMLAttributes } from '@/internal/html-attributes';
	import type { PropsWithElement } from '@/internal/props-with-element';

	export interface TagsInputHiddenInputProps extends PropsWithElement<'input'>, HTMLAttributes<'input', 'children'> {}
</script>

<script lang="ts">
	import { TagsInputRootContext } from '../modules/root-context';
	import { classesTagsInput } from '@skeletonlabs/skeleton-common';
	import { mergeProps } from '@zag-js/svelte';

	const props: TagsInputHiddenInputProps = $props();

	const tagsInput = TagsInputRootContext.consume();

	const { element, ...rest } = $derived(props);

	const attributes = $derived(
		mergeProps(tagsInput().getHiddenInputProps(), rest, {
			class: classesTagsInput.hiddenInput,
		}),
	);
</script>

{#if element}
	{@render element(attributes)}
{:else}
	<input {...attributes} />
{/if}
