// packages/skeleton-react/src/lib/components/Rating/Rating.tsx
import * as rating from '@zag-js/rating-group';
import { useMachine, normalizeProps } from '@zag-js/react';
import { useId, type FC } from 'react';
import type { RatingProps } from './types';
import { starEmpty, starHalf, starFull } from '../../internal/nodes';
import { noop } from '../../internal/noop';

export const Rating: FC<RatingProps> = ({
	// Root
	base = '',
	classes = '',
	// Control
	controlBase = 'flex',
	controlGap = 'gap-2',
	controlClasses,
	// Label
	labelBase = '',
	labelClasses = '',
	// Item
	itemBase = '',
	itemClasses = '',
	// State
	stateInteractive = 'cursor-pointer',
	stateReadOnly = '',
	stateDisabled = 'cursor-not-allowed opacity-50',
	// Icons
	iconEmpty = starEmpty,
	iconHalf = starHalf,
	iconFull = starFull,
	// Children
	label,
	// Events
	onValueChange = noop,
	// Zag
	...zagProps
}) => {
	// Machine
	const [state, send] = useMachine(
		rating.machine({
			id: useId(),
			onValueChange: (details) => onValueChange(details.value)
		}),
		{
			context: zagProps
		}
	);

	// API
	const api = rating.connect(state, send, normalizeProps);

	// Reactive
	const rxInteractive = state.context.isInteractive ? stateInteractive : '';
	const rxReadOnly = state.context.readOnly ? stateReadOnly : '';
	const rxDisabled = state.context.disabled ? stateDisabled : '';

	return (
		<div {...api.getRootProps()} className={`${base} ${classes}`} data-testid="rating">
			{/* Label */}
			{!!label && (
				<label {...api.getLabelProps()} className={`${labelBase} ${labelClasses}`} data-testid="rating-label">
					{label}
				</label>
			)}
			{/* Control */}
			<div
				{...api.getControlProps()}
				className={`${controlBase} ${controlGap} ${rxInteractive} ${rxReadOnly} ${rxDisabled} ${controlClasses}`}
				data-testid="rating-control"
			>
				{api.items.map((index) => {
					const itemState = api.getItemState({ index });
					const icon = (() => {
						if (!itemState.highlighted) {
							return iconEmpty;
						} else if (itemState.half) {
							return iconHalf;
						} else {
							return iconFull;
						}
					})();
					return (
						<>
							{/* Item */}
							<span key={index} {...api.getItemProps({ index })} className={`${itemBase} ${itemClasses}`} data-testid="rating-item">
								{icon}
							</span>
						</>
					);
				})}
			</div>
			{/* Hidden Input */}
			<input {...api.getHiddenInputProps()} data-testid="rating-input" />
		</div>
	);
};

// packages/skeleton-svelte/src/lib/components/Rating/Rating.svelte
<script lang="ts">
	import * as rating from '@zag-js/rating-group';
	import { useMachine, normalizeProps } from '@zag-js/svelte';
	import { useId } from '$lib/internal/use-id.js';
	import { starEmpty, starHalf, starFull } from '$lib/internal/snippets.js';
	import type { RatingProps } from './types.js';
	import { noop } from '$lib/internal/noop.js';

	// Props
	let {
		value = $bindable(),
		// Root
		base = '',
		classes = '',
		// Control
		controlBase = 'flex',
		controlGap = 'gap-2',
		controlClasses,
		// Label
		labelBase = '',
		labelClasses = '',
		// Item
		itemBase = '',
		itemClasses = '',
		// State
		stateInteractive = 'cursor-pointer',
		stateReadOnly = '',
		stateDisabled = 'cursor-not-allowed opacity-50',
		// Icons
		iconEmpty = starEmpty,
		iconHalf = starHalf,
		iconFull = starFull,
		// Children
		label,
		// Events
		onValueChange = noop,
		// Zag
		...zagProps
	}: RatingProps = $props();

	// Machine
	const [state, send] = useMachine(
		rating.machine({
			id: useId(),
			onValueChange: (details) => {
				value = details.value;
				onValueChange(details.value);
			}
		}),
		{
			context: {
				...zagProps,
				get value() {
					return value;
				}
			}
		}
	);

	// API
	const api = $derived(rating.connect(state, send, normalizeProps));

	// Reactive
	const rxInteractive = $derived(state.context.isInteractive ? stateInteractive : '');
	const rxReadOnly = $derived(state.context.readOnly ? stateReadOnly : '');
	const rxDisabled = $derived(state.context.disabled ? stateDisabled : '');
</script>

<!-- @component A rating component. -->

<!-- Root -->
<div class="{base} {classes}" {...api.getRootProps()} data-testid="rating">
	<!-- Label -->
	{#if !!label}
		<label class="{labelBase} {labelClasses}" {...api.getLabelProps()} data-testid="rating-label">
			{@render label()}
		</label>
	{/if}
	<!-- Control -->
	<div
		class="{controlBase} {controlGap} {rxInteractive} {rxReadOnly} {rxDisabled} {controlClasses}"
		{...api.getControlProps()}
		data-testid="rating-control"
	>
		{#each api.items as index}
			{@const itemState = api.getItemState({ index })}
			<!-- Item -->
			<span class="{itemBase} {itemClasses}" {...api.getItemProps({ index })} data-testid="rating-item">
				{#if !itemState.highlighted}
					{@render iconEmpty()}
				{:else if itemState.half}
					{@render iconHalf()}
				{:else}
					{@render iconFull()}
				{/if}
			</span>
		{/each}
	</div>
	<!-- Hidden Input -->
	<input {...api.getHiddenInputProps()} data-testid="rating-input" />
</div>
