// sites/skeleton.dev/src/components/examples/framework-components/segmented-control/svelte/controlled.svelte
<script lang="ts">
	import { SegmentedControl } from '@skeletonlabs/skeleton-svelte';

	let value = $state<string | null>('item-1');
</script>

<div class="flex flex-col items-center gap-4">
	<SegmentedControl {value} onValueChange={(details) => (value = details.value)}>
		<SegmentedControl.Control>
			<SegmentedControl.Indicator />
			{#each ['item-1', 'item-2', 'item-3'] as item (item)}
				<SegmentedControl.Item value={item}>
					<SegmentedControl.ItemText>{item}</SegmentedControl.ItemText>
					<SegmentedControl.ItemHiddenInput />
				</SegmentedControl.Item>
			{/each}
		</SegmentedControl.Control>
	</SegmentedControl>
	<pre class="pre">{value}</pre>
</div>

// sites/skeleton.dev/src/components/examples/framework-components/segmented-control/react/controlled.tsx
import { SegmentedControl } from '@skeletonlabs/skeleton-react';
import { useState } from 'react';

export default function Controlled() {
	const [value, setValue] = useState<string | null>('item-1');

	return (
		<div className="flex flex-col items-center gap-4">
			<SegmentedControl value={value} onValueChange={(details) => setValue(details.value)}>
				<SegmentedControl.Control>
					<SegmentedControl.Indicator />
					{['item-1', 'item-2', 'item-3'].map((item) => (
						<SegmentedControl.Item value={item} key={item}>
							<SegmentedControl.ItemText>{item}</SegmentedControl.ItemText>
							<SegmentedControl.ItemHiddenInput />
						</SegmentedControl.Item>
					))}
				</SegmentedControl.Control>
			</SegmentedControl>
			<pre className="pre">{value}</pre>
		</div>
	);
}
