// packages/skeleton-react/src/components/file-upload/anatomy/file-upload-item.tsx
import { useContext, type ComponentProps, type PropsWithChildren } from 'react';
import { splitItemProps, type ItemProps } from '@zag-js/file-upload';
import { mergeProps } from '@zag-js/react';
import { classesFileUpload } from '@skeletonlabs/skeleton-common';
import { FileUploadRootContext } from '../modules/file-upload-root-context';
import { FileUploadItemContext } from '../modules/file-upload-item-context';
import type { PropsWithElement } from '@/internal/props-with-element';

export interface FileUploadItemProps extends PropsWithChildren, PropsWithElement, ItemProps, ComponentProps<'li'> {}

export default function (props: FileUploadItemProps) {
	const rootContext = useContext(FileUploadRootContext);
	const [itemProps, componentProps] = splitItemProps(props);
	const { element, children, ...restAttributes } = componentProps;
	const attributes = mergeProps(
		rootContext.api.getItemProps(itemProps),
		{
			className: classesFileUpload.item
		},
		restAttributes
	);
	return (
		<FileUploadItemContext.Provider value={{ itemProps }}>
			{element ? element({ attributes }) : <li {...attributes}>{children}</li>}
		</FileUploadItemContext.Provider>
	);
}

// packages/skeleton-svelte/src/components/file-upload/anatomy/file-upload-item.svelte
<script lang="ts" module>
	import type { HTMLAttributes } from 'svelte/elements';
	import type { PropsWithElement } from '@/internal/props-with-element';
	import type { ItemProps } from '@zag-js/file-upload';

	export interface FileUploadItemProps extends PropsWithElement, ItemProps, HTMLAttributes<HTMLLIElement> {}
</script>

<script lang="ts">
	import { classesFileUpload } from '@skeletonlabs/skeleton-common';
	import { FileUploadRootContext } from '../modules/file-upload-root-context';
	import { FileUploadItemContext } from '../modules/file-upload-item-context';
	import { mergeProps } from '@zag-js/svelte';

	const props: FileUploadItemProps = $props();
	const rootContext = FileUploadRootContext.consume();
	const { element, children, ...restAttributes } = $derived(props);
	const attributes = $derived(mergeProps(rootContext.api.getItemProps(props), { class: classesFileUpload.item }, restAttributes));
	FileUploadItemContext.provide({ itemProps: props });
</script>

{#if element}
	{@render element({ attributes })}
{:else}
	<li {...attributes}>
		{@render children?.()}
	</li>
{/if}
