// packages/skeleton-react/src/components/file-upload/anatomy/item-context.tsx
import { useContext, type ReactNode } from 'react';
import { FileUploadItemContext, type FileUploadItemContextType } from '../modules/item-context';

export interface FileUploadItemContextProps {
	children: (context: FileUploadItemContextType) => ReactNode;
}

export default function (props: FileUploadItemContextProps) {
	const itemContext = useContext(FileUploadItemContext);

	return props.children(itemContext);
}

// packages/skeleton-svelte/src/components/file-upload/anatomy/item-context.svelte
<script lang="ts" module>
	import type { Snippet } from 'svelte';
	import type { FileUploadItemContextType } from '../modules/item-context';

	export interface FileUploadItemContextProps {
		children: Snippet<[FileUploadItemContextType]>;
	}
</script>

<script lang="ts">
	import { FileUploadItemContext } from '../modules/item-context';

	const props: FileUploadItemContextProps = $props();

	const itemContext = FileUploadItemContext.consume();
</script>

{@render props.children(itemContext)}
