// packages/skeleton-svelte/src/components/toast/anatomy/close-trigger.svelte
<script lang="ts" module>
	import type { HTMLAttributes } from '@/internal/html-attributes';
	import type { PropsWithElement } from '@/internal/props-with-element';

	export interface ToastCloseTriggerProps extends PropsWithElement<'button'>, HTMLAttributes<'button'> {}
</script>

<script lang="ts">
	import { RootContext } from '../modules/root-context';
	import X from '@/internal/components/x.svelte';
	import { classesToast } from '@skeletonlabs/skeleton-common';
	import { mergeProps } from '@zag-js/svelte';

	const props: ToastCloseTriggerProps = $props();

	const toast = RootContext.consume();

	const { element, children = x, ...rest } = $derived(props);

	const attributes = $derived(
		mergeProps(
			toast().getCloseTriggerProps(),
			{
				class: classesToast.closeTrigger,
			},
			rest,
		),
	);
</script>

{#snippet x()}
	<X />
{/snippet}

{#if element}
	{@render element(attributes)}
{:else}
	<button {...attributes}>
		{@render children?.()}
	</button>
{/if}

// packages/skeleton-react/src/components/toast/anatomy/close-trigger.tsx
import { RootContext } from '../modules/root-context.js';
import X from '../../../internal/components/x.js';
import type { HTMLAttributes } from '../../../internal/html-attributes.js';
import type { PropsWithElement } from '../../../internal/props-with-element.js';
import { classesToast } from '@skeletonlabs/skeleton-common';
import { mergeProps } from '@zag-js/react';
import { use } from 'react';

export interface ToastCloseTriggerProps extends PropsWithElement<'button'>, HTMLAttributes<'button'> {}

export default function CloseTrigger(props: ToastCloseTriggerProps) {
	const toast = use(RootContext);

	const { element, children = <X />, ...rest } = props;

	const attributes = mergeProps(
		toast.getCloseTriggerProps(),
		{
			className: classesToast.closeTrigger,
		},
		rest,
	);

	return element ? element(attributes) : <button {...attributes}>{children}</button>;
}
