// packages/skeleton-svelte/src/components/toast/anatomy/toast-root-context.svelte
<script lang="ts" module>
	import type { Snippet } from 'svelte';
	import type { ToastRootContextType } from '../modules/toast-root-context';

	export interface ToastRootContextProps {
		children: Snippet<[ToastRootContextType]>;
	}
</script>

<script lang="ts">
	import { ToastRootContext } from '../modules/toast-root-context';

	const props: ToastRootContextProps = $props();
	const rootContext = ToastRootContext.consume();
</script>

{@render props.children(rootContext)}

// packages/skeleton-react/src/components/toast/anatomy/toast-root-context.tsx
import { useContext, type ReactNode } from 'react';
import { ToastRootContext, type ToastRootContextType } from '../modules/toast-root-context';

export interface ToastRootContextProps {
	children: (context: ToastRootContextType) => ReactNode;
}

export default function (props: ToastRootContextProps) {
	const rootContext = useContext(ToastRootContext);
	return props.children(rootContext);
}
