// sites/skeleton.dev/src/examples/components/switch/ExampleCompact.svelte
<script lang="ts">
	import { Switch } from '@skeletonlabs/skeleton-svelte';
	// Icons
	import IconFrown from '@lucide/svelte/icons/frown';
	import IconSmile from '@lucide/svelte/icons/smile';
</script>

<Switch name="compact" controlWidth="w-9" controlActive="preset-filled-tertiary-500" compact>
	{#snippet inactiveChild()}<IconFrown size="20" />{/snippet}
	{#snippet activeChild()}<IconSmile size="20" />{/snippet}
</Switch>

// sites/next.skeleton.dev/src/examples/components/switch/ExampleCompact.tsx
import React from 'react';
import { Switch } from '@skeletonlabs/skeleton-react';
import { Frown as IconFrown, Smile as IconSmile } from 'lucide-react';

export const Page: React.FC = () => {
	const [compact, setCompact] = React.useState(false);

	return (
		<Switch
			name="compact"
			checked={compact}
			onCheckedChange={(e) => setCompact(e.checked)}
			controlWidth="w-9"
			controlActive="preset-filled-tertiary-500"
			compact
			inactiveChild={<IconFrown size="18" />}
			activeChild={<IconSmile size="18" />}
		/>
	);
};
