// packages/skeleton-react/src/components/navigation/anatomy/trigger-anchor.tsx
import type { HTMLAttributes } from '../../../internal/html-attributes.js';
import type { PropsWithElement } from '../../../internal/props-with-element.js';
import { NavigationRootContext } from '../modules/root-context.js';
import { mergeProps } from '@zag-js/react';
import { use } from 'react';

export interface NavigationTriggerAnchorProps extends PropsWithElement<'a'>, HTMLAttributes<'a'> {}

export default function NavigationTriggerAnchor(props: NavigationTriggerAnchorProps) {
	const { element, children, ...rest } = props;

	const navigation = use(NavigationRootContext);

	const attributes = mergeProps(
		{
			'data-scope': 'navigation',
			'data-part': 'trigger-anchor',
			'data-layout': navigation.layout,
		},
		rest,
	);

	return element ? element(attributes) : <a {...attributes}>{children}</a>;
}

// packages/skeleton-svelte/src/components/navigation/anatomy/trigger-anchor.svelte
<script lang="ts" module>
	import type { HTMLAttributes } from '../../../internal/html-attributes.js';
	import type { PropsWithElement } from '../../../internal/props-with-element.js';

	export interface NavigationTriggerAnchorProps extends PropsWithElement<'anchor'>, HTMLAttributes<'anchor'> {}
</script>

<script lang="ts">
	import { NavigationRootContext } from '../modules/root-context.js';
	import { mergeProps } from '@zag-js/svelte';

	const props: NavigationTriggerAnchorProps = $props();

	const navigation = NavigationRootContext.consume();

	const { element, children, ...rest } = $derived(props);

	const attributes = $derived(
		mergeProps(
			{
				'data-scope': 'navigation',
				'data-part': 'trigger-anchor',
				'data-layout': navigation().layout,
			},
			rest,
		),
	);
</script>

{#if element}
	{@render element(attributes)}
{:else}
	<a {...attributes}>
		{@render children?.()}
	</a>
{/if}
