// packages/skeleton-react/src/components/navigation/anatomy/trigger.tsx
import type { HTMLAttributes } from '../../../internal/html-attributes.js';
import type { PropsWithElement } from '../../../internal/props-with-element.js';
import { NavigationRootContext } from '../modules/root-context.js';
import { mergeProps } from '@zag-js/react';
import { use } from 'react';

export interface NavigationTriggerProps extends PropsWithElement<'button'>, HTMLAttributes<'button'> {}

export default function NavigationTrigger(props: NavigationTriggerProps) {
	const { element, children, ...rest } = props;

	const navigation = use(NavigationRootContext);

	const attributes = mergeProps(
		{
			'data-scope': 'navigation',
			'data-part': 'trigger',
			'data-layout': navigation.layout,
			type: 'button',
		},
		rest,
	);

	return element ? element(attributes) : <button {...attributes}>{children}</button>;
}

// packages/skeleton-svelte/src/components/navigation/anatomy/trigger.svelte
<script lang="ts" module>
	import type { HTMLAttributes } from '../../../internal/html-attributes.js';
	import type { PropsWithElement } from '../../../internal/props-with-element.js';

	export interface NavigationTriggerProps extends PropsWithElement<'button'>, HTMLAttributes<'button'> {}
</script>

<script lang="ts">
	import { NavigationRootContext } from '../modules/root-context.js';
	import { mergeProps } from '@zag-js/svelte';

	const props: NavigationTriggerProps = $props();

	const navigation = NavigationRootContext.consume();

	const { element, children, ...rest } = $derived(props);

	const attributes = $derived(
		mergeProps(
			{
				'data-scope': 'navigation',
				'data-part': 'trigger',
				'data-layout': navigation().layout,
				type: 'button',
			},
			rest,
		),
	);
</script>

{#if element}
	{@render element(attributes)}
{:else}
	<button type="button" {...attributes}>
		{@render children?.()}
	</button>
{/if}
