// packages/skeleton-svelte/src/components/tooltip/anatomy/tooltip-trigger.svelte
<script lang="ts" module>
	import type { PropsWithElement } from '@/internal/props-with-element';
	import type { HTMLButtonAttributes } from 'svelte/elements';

	export interface TooltipTriggerProps extends PropsWithElement, HTMLButtonAttributes {}
</script>

<script lang="ts">
	import { mergeProps } from '@zag-js/svelte';
	import { classesTooltip } from '@skeletonlabs/skeleton-common';
	import { TooltipRootContext } from '../modules/tooltip-root-context';

	const props: TooltipTriggerProps = $props();
	const rootContext = TooltipRootContext.consume();
	const { element, children, ...restAttributes } = $derived(props);
	const attributes = $derived(mergeProps(rootContext.api.getTriggerProps(), { class: classesTooltip.trigger }, restAttributes));
</script>

{#if element}
	{@render element({ attributes })}
{:else}
	<button {...attributes}>
		{@render children?.()}
	</button>
{/if}

// packages/skeleton-react/src/components/tooltip/anatomy/tooltip-trigger.tsx
import { mergeProps } from '@zag-js/react';
import { useContext, type ComponentProps } from 'react';
import { TooltipRootContext } from '../modules/tooltip-root-context.js';
import { classesTooltip } from '@skeletonlabs/skeleton-common';
import type { PropsWithElement } from '@/internal/props-with-element.js';

export interface TooltipTriggerProps extends PropsWithElement, ComponentProps<'button'> {}

export default function (props: TooltipTriggerProps) {
	const rootContext = useContext(TooltipRootContext);
	const { element, children, ...restAttributes } = props;
	const attributes = mergeProps(
		rootContext.api.getTriggerProps(),
		{
			className: classesTooltip.trigger
		},
		restAttributes
	);
	return element ? element({ attributes }) : <button {...attributes}>{children}</button>;
}
