// playgrounds/skeleton-react/src/routes/components/rating-group/index.tsx
'use client';

import { RatingGroup } from '@skeletonlabs/skeleton-react';
import { createFileRoute } from '@tanstack/react-router';

export const Route = createFileRoute('/components/rating-group/')({
	component: Page,
});

function Page() {
	return (
		<RatingGroup count={10} allowHalf defaultValue={7.5}>
			<RatingGroup.Label>Label</RatingGroup.Label>
			<RatingGroup.Control>
				<RatingGroup.Context>
					{(ratingGroup) => ratingGroup.items.map((index) => <RatingGroup.Item key={index} index={index} />)}
				</RatingGroup.Context>
			</RatingGroup.Control>
			<RatingGroup.HiddenInput />
		</RatingGroup>
	)
}

// playgrounds/skeleton-svelte/src/routes/components/rating-group/+page.svelte
<script lang="ts">
	import { RatingGroup } from '@skeletonlabs/skeleton-svelte';
	import StarIcon from '@lucide/svelte/icons/star';
</script>

<RatingGroup count={5}>
	<RatingGroup.Control>
		<RatingGroup.Context>
			{#snippet children({ items })}
				{#each items as index (index)}
					<RatingGroup.Item {index}>
						<RatingGroup.ItemContext>
							{#snippet children({ highlighted })}
								{#if highlighted}
									<StarIcon fill="currentColor" />
								{:else}
									<StarIcon />
								{/if}
							{/snippet}
						</RatingGroup.ItemContext>
					</RatingGroup.Item>
				{/each}
			{/snippet}
		</RatingGroup.Context>
	</RatingGroup.Control>
	<RatingGroup.HiddenInput />
</RatingGroup>
