// packages/skeleton-react/src/components/combobox/anatomy/combobox-content.tsx
import { useContext, type ComponentProps } from 'react';
import { mergeProps } from '@zag-js/react';
import { ComboboxRootContext } from '../modules/combobox-root-context';
import { classesCombobox } from '@skeletonlabs/skeleton-common';
import type { PropsWithElement } from '@/internal/props-with-element';

export interface ComboboxContentProps extends PropsWithElement, ComponentProps<'ul'> {}

export default function (props: ComboboxContentProps) {
	const rootContext = useContext(ComboboxRootContext);
	const { element, children, ...restAttributes } = props;
	const attributes = mergeProps(rootContext.api.getContentProps(), { className: classesCombobox.content }, restAttributes);
	return element ? element({ attributes }) : <ul {...attributes}>{children}</ul>;
}

// packages/skeleton-svelte/src/components/combobox/anatomy/combobox-content.svelte
<script lang="ts" module>
	import type { PropsWithElement } from '@/internal/props-with-element';
	import type { HTMLAttributes } from 'svelte/elements';

	export interface ComboboxContentProps extends PropsWithElement, HTMLAttributes<HTMLUListElement> {}
</script>

<script lang="ts">
	import { mergeProps } from '@zag-js/svelte';
	import { classesCombobox } from '@skeletonlabs/skeleton-common';
	import { ComboboxRootContext } from '../modules/combobox-root-context';

	const props: ComboboxContentProps = $props();
	const rootContext = ComboboxRootContext.consume();
	const { element, children, ...restAttributes } = $derived(props);
	const attributes = $derived(mergeProps(rootContext.api.getContentProps(), { class: classesCombobox.content }, restAttributes));
</script>

{#if element}
	{@render element({ attributes })}
{:else}
	<ul {...attributes}>
		{@render children?.()}
	</ul>
{/if}
