// packages/skeleton-react/src/components/combobox/anatomy/combobox-root-context.tsx
import { useContext, type ReactNode } from 'react';
import { ComboboxRootContext, type ComboboxRootContextType } from '../modules/combobox-root-context';

export interface ComboboxRootContextProps {
	children: (context: ComboboxRootContextType) => ReactNode;
}

export default function (props: ComboboxRootContextProps) {
	const rootContext = useContext(ComboboxRootContext);
	return props.children(rootContext);
}

// packages/skeleton-svelte/src/components/combobox/anatomy/combobox-root-context.svelte
<script lang="ts" module>
	import type { Snippet } from 'svelte';
	import type { ComboboxRootContextType } from '../modules/combobox-root-context';

	export interface ComboboxRootContextProps {
		children: Snippet<[ComboboxRootContextType]>;
	}
</script>

<script lang="ts">
	import { ComboboxRootContext } from '../modules/combobox-root-context';

	const props: ComboboxRootContextProps = $props();
	const rootContext = ComboboxRootContext.consume();
</script>

{@render props.children(rootContext)}
