// packages/skeleton-react/src/components/combobox/anatomy/combobox-positioner.tsx
import { useContext, type ComponentProps } from 'react';
import { mergeProps, Portal } from '@zag-js/react';
import { ComboboxRootContext } from '../modules/combobox-root-context';
import { classesCombobox } from '@skeletonlabs/skeleton-common';
import type { PropsWithElement } from '@/internal/props-with-element';

export interface ComboboxPositionerProps extends PropsWithElement, ComponentProps<'div'> {}

export default function (props: ComboboxPositionerProps) {
	const rootContext = useContext(ComboboxRootContext);
	const { element, children, ...restAttributes } = props;
	const attributes = mergeProps(rootContext.api.getPositionerProps(), { className: classesCombobox.positioner }, restAttributes);
	return <Portal>{element ? element({ attributes }) : <div {...attributes}>{children}</div>}</Portal>;
}

// packages/skeleton-svelte/src/components/combobox/anatomy/combobox-positioner.svelte
<script lang="ts" module>
	import type { PropsWithElement } from '@/internal/props-with-element';
	import type { HTMLAttributes } from 'svelte/elements';

	export interface ComboboxPositionerProps extends PropsWithElement, HTMLAttributes<HTMLDivElement> {}
</script>

<script lang="ts">
	import { mergeProps, portal } from '@zag-js/svelte';
	import { classesCombobox } from '@skeletonlabs/skeleton-common';
	import { ComboboxRootContext } from '../modules/combobox-root-context';
	import { createAttachmentKey, fromAction } from 'svelte/attachments';

	const props: ComboboxPositionerProps = $props();
	const rootContext = ComboboxRootContext.consume();
	const { element, children, ...restAttributes } = $derived(props);
	const attributes = $derived({
		...mergeProps(rootContext.api.getPositionerProps(), { class: classesCombobox.positioner }, restAttributes),
		[createAttachmentKey()]: fromAction(portal, () => undefined)
	});
</script>

{#if element}
	{@render element({ attributes })}
{:else}
	<div {...attributes}>
		{@render children?.()}
	</div>
{/if}
