// packages/skeleton-svelte/src/components/marquee/anatomy/edge.svelte
<script lang="ts" module>
	import type { HTMLAttributes } from '../../../internal/html-attributes.js';
	import type { PropsWithElement } from '../../../internal/props-with-element.js';
	import type { EdgeProps } from '@zag-js/marquee';

	export interface MarqueeEdgeProps extends EdgeProps, PropsWithElement<'div'>, HTMLAttributes<'div'> {}
</script>

<script lang="ts">
	import { MarqueeRootContext } from '../modules/root-context.js';
	import { mergeProps } from '@zag-js/svelte';

	const props: MarqueeEdgeProps = $props();

	const marquee = MarqueeRootContext.consume();

	const { element, children, side, ...rest } = $derived(props);

	const attributes = $derived(mergeProps(marquee().getEdgeProps({ side }), rest));
</script>

{#if element}
	{@render element(attributes)}
{:else}
	<div {...attributes}>
		{@render children?.()}
	</div>
{/if}

// packages/skeleton-react/src/components/marquee/anatomy/edge.tsx
import type { HTMLAttributes } from '../../../internal/html-attributes.js';
import type { PropsWithElement } from '../../../internal/props-with-element.js';
import { MarqueeRootContext } from '../modules/root-context.js';
import { mergeProps } from '@zag-js/react';
import type { EdgeProps } from '@zag-js/marquee';
import { type PropsWithChildren, use } from 'react';

export interface MarqueeEdgeProps extends EdgeProps, PropsWithChildren, PropsWithElement<'div'>, HTMLAttributes<'div'> {}

export default function Edge(props: MarqueeEdgeProps) {
	const marquee = use(MarqueeRootContext);

	const { element, children, side, ...rest } = props;

	const attributes = mergeProps(marquee.getEdgeProps({ side }), rest);

	return element ? element(attributes) : <div {...attributes}>{children}</div>;
}
