// packages/skeleton-react/src/components/avatar/anatomy/avatar-image.tsx
import { useContext, type ComponentProps } from 'react';
import { mergeProps } from '@zag-js/react';
import { AvatarRootContext } from '../modules/avatar-root-context';
import { classesAvatar } from '@skeletonlabs/skeleton-common';
import type { PropsWithElement } from '@/internal/props-with-element';

export interface AvatarImageProps extends PropsWithElement, Omit<ComponentProps<'img'>, 'children'> {}

export default function (props: AvatarImageProps) {
	const rootContext = useContext(AvatarRootContext);
	const { element, ...restAttributes } = props;
	const attributes = mergeProps(rootContext.api.getImageProps(), { className: classesAvatar.image }, restAttributes);
	return element ? element({ attributes }) : <img {...attributes} />;
}

// packages/skeleton-svelte/src/components/avatar/anatomy/avatar-image.svelte
<script lang="ts" module>
	import type { PropsWithElement } from '@/internal/props-with-element';
	import type { HTMLImgAttributes } from 'svelte/elements';

	export interface AvatarImageProps extends PropsWithElement, HTMLImgAttributes {}
</script>

<script lang="ts">
	import { mergeProps } from '@zag-js/svelte';
	import { classesAvatar } from '@skeletonlabs/skeleton-common';
	import { AvatarRootContext } from '../modules/avatar-root-context';

	const props: AvatarImageProps = $props();
	const rootContext = AvatarRootContext.consume();
	const { element, ...restAttributes } = $derived(props);
	const attributes = $derived(
		mergeProps(
			rootContext.api.getImageProps(),
			{
				class: classesAvatar.image
			},
			restAttributes
		)
	);
</script>

{#if element}
	{@render element({ attributes })}
{:else}
	<img {...attributes} />
{/if}
