// sites/skeleton.dev/src/examples/components/progress-circular/react/color.tsx
import { Progress } from '@skeletonlabs/skeleton-react';

export default function Color() {
	return (
		<div className="flex gap-4 justify-evenly items-center w-full">
			<Progress className="w-fit">
				<Progress.Circle>
					<Progress.CircleTrack />
					<Progress.CircleRange className="stroke-primary-500" />
				</Progress.Circle>
			</Progress>
			<Progress className="w-fit">
				<Progress.Circle>
					<Progress.CircleTrack />
					<Progress.CircleRange className="stroke-secondary-500" />
				</Progress.Circle>
			</Progress>
			<Progress className="w-fit">
				<Progress.Circle>
					<Progress.CircleTrack />
					<Progress.CircleRange className="stroke-tertiary-500" />
				</Progress.Circle>
			</Progress>
		</div>
	);
}

// sites/skeleton.dev/src/examples/components/progress-circular/svelte/color.svelte
<script lang="ts">
	import { Progress } from '@skeletonlabs/skeleton-svelte';
</script>

<div class="flex gap-4 justify-evenly items-center w-full">
	<Progress class="w-fit">
		<Progress.Circle>
			<Progress.CircleTrack />
			<Progress.CircleRange class="stroke-primary-500" />
		</Progress.Circle>
	</Progress>
	<Progress class="w-fit">
		<Progress.Circle>
			<Progress.CircleTrack />
			<Progress.CircleRange class="stroke-secondary-500" />
		</Progress.Circle>
	</Progress>
	<Progress class="w-fit">
		<Progress.Circle>
			<Progress.CircleTrack />
			<Progress.CircleRange class="stroke-tertiary-500" />
		</Progress.Circle>
	</Progress>
</div>
