// packages/skeleton-react/src/components/switch/anatomy/switch-root-context.tsx
import { useContext, type ReactNode } from 'react';
import { SwitchRootContext, type SwitchRootContextType } from '../modules/switch-root-context';

export interface SwitchRootContextProps {
	children: (context: SwitchRootContextType) => ReactNode;
}

export default function (props: SwitchRootContextProps) {
	const rootContext = useContext(SwitchRootContext);
	return props.children(rootContext);
}

// packages/skeleton-svelte/src/components/switch/anatomy/switch-root-context.svelte
<script lang="ts" module>
	import type { Snippet } from 'svelte';
	import type { SwitchRootContextType } from '../modules/switch-root-context';

	export interface SwitchRootContextProps {
		children: Snippet<[SwitchRootContextType]>;
	}
</script>

<script lang="ts">
	import { SwitchRootContext } from '../modules/switch-root-context';

	const props: SwitchRootContextProps = $props();
	const rootContext = SwitchRootContext.consume();
</script>

{@render props.children(rootContext)}
