// packages/skeleton-react/src/components/switch/anatomy/switch-thumb.tsx
'use client';

import { useContext, type ComponentProps } from 'react';
import { mergeProps } from '@zag-js/react';
import { SwitchRootContext } from '../modules/switch-root-context';
import { classesSwitch } from '@skeletonlabs/skeleton-common';
import type { PropsWithElement } from '@/internal/props-with-element';

export interface SwitchThumbProps extends PropsWithElement, Omit<ComponentProps<'span'>, 'children'> {}

export default function (props: SwitchThumbProps) {
	const rootContext = useContext(SwitchRootContext);
	const { element, ...restAttributes } = props;
	const attributes = mergeProps(rootContext.api.getThumbProps(), { className: classesSwitch.thumb }, restAttributes);
	return element ? element({ attributes }) : <span {...attributes} />;
}

// packages/skeleton-svelte/src/components/switch/anatomy/switch-thumb.svelte
<script lang="ts" module>
	import type { PropsWithElement } from '@/internal/props-with-element';
	import type { HTMLAttributes } from 'svelte/elements';

	export interface SwitchThumbProps extends PropsWithElement, HTMLAttributes<HTMLSpanElement> {}
</script>

<script lang="ts">
	import { mergeProps } from '@zag-js/svelte';
	import { classesSwitch } from '@skeletonlabs/skeleton-common';
	import { SwitchRootContext } from '../modules/switch-root-context';

	const props: SwitchThumbProps = $props();
	const rootContext = SwitchRootContext.consume();
	const { element, children, ...restAttributes } = $derived(props);
	const attributes = $derived(
		mergeProps(
			rootContext.api.getThumbProps(),
			{
				class: classesSwitch.thumb
			},
			restAttributes
		)
	);
</script>

{#if element}
	{@render element({ attributes })}
{:else}
	<span {...attributes}>
		{@render children?.()}
	</span>
{/if}
