// packages/skeleton-svelte/src/components-new/accordion/anatomy/accordion-heading.svelte
<script lang="ts">
	import type { AccordionHeadingProps } from '../modules/types.js';

	const props: AccordionHeadingProps = $props();
	const { level = 3, children, ...restAttributes } = $derived(props);
	const tag = $derived(`h${level}`);
</script>

<svelte:element this={tag} {...restAttributes}>
	{@render children?.()}
</svelte:element>

// packages/skeleton-react/src/composed/accordion/anatomy/accordion-heading.tsx
import type { JSX } from 'react';
import type { AccordionHeadingProps } from '../modules/types.js';

export default function (props: AccordionHeadingProps) {
	const { level = 3, element, children, ...restAttributes } = props;
	const Tag: keyof JSX.IntrinsicElements = `h${level}`;
	return element ? element({ attributes: restAttributes }) : <Tag {...restAttributes}>{children}</Tag>;
}
