// sites/skeleton.dev/src/examples/components/rating-group/svelte/label.svelte
<script lang="ts">
	import { RatingGroup } from '@skeletonlabs/skeleton-svelte';
</script>

<RatingGroup count={5}>
	<RatingGroup.Label>Rate us:</RatingGroup.Label>
	<RatingGroup.Control>
		{#each Array.from({ length: 5 }), index}
			<RatingGroup.Item index={index + 1} />
		{/each}
	</RatingGroup.Control>
	<RatingGroup.HiddenInput />
</RatingGroup>

// sites/skeleton.dev/src/examples/components/rating-group/react/label.tsx
'use client';

import { RatingGroup } from '@skeletonlabs/skeleton-react';

export default function () {
	return (
		<RatingGroup count={5}>
			<RatingGroup.Label>Rate us:</RatingGroup.Label>
			<RatingGroup.Control>
				{Array.from({ length: 5 }).map((_, index) => (
					<RatingGroup.Item key={index} index={index + 1} />
				))}
			</RatingGroup.Control>
			<RatingGroup.HiddenInput />
		</RatingGroup>
	);
}
