// packages/skeleton-react/src/components/app-bar/anatomy/headline.tsx
import type { HTMLAttributes } from '../../../internal/html-attributes.js';
import type { PropsWithElement } from '../../../internal/props-with-element.js';
import { mergeProps } from '@zag-js/react';

export interface AppBarHeadlineProps extends PropsWithElement<'div'>, HTMLAttributes<'div'> {}

export default function AppBarHeadline(props: AppBarHeadlineProps) {
	const { element, children, ...rest } = props;

	const attributes = mergeProps(
		{
			'data-scope': 'app-bar',
			'data-part': 'headline',
		},
		rest,
	);

	return element ? element(attributes) : <div {...attributes}>{children}</div>;
}

// packages/skeleton-svelte/src/components/app-bar/anatomy/headline.svelte
<script lang="ts" module>
	import type { HTMLAttributes } from '../../../internal/html-attributes.js';
	import type { PropsWithElement } from '../../../internal/props-with-element.js';

	export interface AppBarHeadlineProps extends PropsWithElement<'div'>, HTMLAttributes<'div'> {}
</script>

<script lang="ts">
	import { mergeProps } from '@zag-js/svelte';

	const props: AppBarHeadlineProps = $props();

	const { element, children, ...rest } = $derived(props);

	const attributes = $derived(
		mergeProps(
			{
				'data-scope': 'app-bar',
				'data-part': 'headline',
			},
			rest,
		),
	);
</script>

{#if element}
	{@render element(attributes)}
{:else}
	<div {...attributes}>
		{@render children?.()}
	</div>
{/if}
