// packages/skeleton-react/src/components-overhaul/accordion/anatomy/accordion-indicator.tsx
import { mergeProps } from '@zag-js/react';
import { useContext } from 'react';
import { AccordionRootContext, AccordionItemContext } from '../modules/context.js';
import type { AccordionIndicatorProps } from '../modules/types.js';

export default function (props: AccordionIndicatorProps) {
	const rootContext = useContext(AccordionRootContext);
	const itemContext = useContext(AccordionItemContext);
	const { child, children, ...restAttributes } = props;
	const attributes = mergeProps(rootContext.api.getItemIndicatorProps(itemContext.itemProps), restAttributes);
	return child ? child({ attributes }) : <div {...attributes}>{children}</div>;
}

// packages/skeleton-svelte/src/components-overhaul/accordion/anatomy/accordion-indicator.svelte
<script lang="ts">
	import { mergeProps } from '@zag-js/svelte';
	import { AccordionRootContext, AccordionItemContext } from '../modules/context.js';
	import type { AccordionIndicatorProps } from '../modules/types.js';

	const rootContext = AccordionRootContext.consume();
	const itemContext = AccordionItemContext.consume();
	const props: AccordionIndicatorProps = $props();
	const { child, children, ...restAttributes } = $derived(props);
	const attributes = $derived(mergeProps(rootContext.api.getItemIndicatorProps(itemContext.itemProps), restAttributes));
</script>

{#if child}
	{@render child(restAttributes)}
{:else}
	<div {...attributes}>
		{@render children?.()}
	</div>
{/if}
