// sites/next.skeleton.dev/src/examples/components/slider/ExampleHeight.svelte
<script lang="ts">
import { Slider } from "@skeletonlabs/skeleton-svelte";

let value = $state([40]);
</script>

<section class="w-full space-y-8">
  <Slider
    name="value"
    {value}
    onValueChange={(e) => (value = e.value)}
    height="h-1"
  />
  <Slider
    name="value"
    {value}
    onValueChange={(e) => (value = e.value)}
    height="h-6"
    thumbSize="size-8"
  />
</section>

// sites/next.skeleton.dev/src/examples/components/progress/ExampleHeight.tsx
import { Progress } from '@skeletonlabs/skeleton-react';

export const Page = () => {
  return (
    <div className="flex w-full flex-col gap-8">
      <Progress value={50} max={100} />
      <Progress value={50} max={100} height="h-4" />
      <Progress value={50} max={100} height="h-8" />
    </div>
  );
};
