// packages/skeleton-react/src/components/date-picker/anatomy/table-body.tsx
import { RootContext } from '../modules/root-context.js';
import { ViewContext } from '../modules/view-context.js';
import type { HTMLAttributes } from '@/internal/html-attributes.js';
import type { PropsWithElement } from '@/internal/props-with-element.js';
import { classesDatePicker } from '@skeletonlabs/skeleton-common';
import { mergeProps } from '@zag-js/react';
import { use } from 'react';

export interface DatePickerTableBodyProps extends PropsWithElement<'tbody'>, HTMLAttributes<'tbody'> {}

export default function TableBody(props: DatePickerTableBodyProps) {
	const datePicker = use(RootContext);
	const viewProps = use(ViewContext);

	const { element, children, ...rest } = props;

	const attributes = mergeProps(
		datePicker.getTableBodyProps(viewProps),
		{
			className: classesDatePicker.tableBody,
		},
		rest,
	);

	return element ? element(attributes) : <tbody {...attributes}>{children}</tbody>;
}

// packages/skeleton-svelte/src/components/date-picker/anatomy/table-body.svelte
<script lang="ts" module>
	import type { HTMLAttributes } from '@/internal/html-attributes';
	import type { PropsWithElement } from '@/internal/props-with-element';

	export interface DatePickerTableBodyProps extends PropsWithElement<'tbody'>, HTMLAttributes<'tbody'> {}
</script>

<script lang="ts">
	import { RootContext } from '../modules/root-context';
	import { ViewContext } from '../modules/view-context';
	import { classesDatePicker } from '@skeletonlabs/skeleton-common';
	import { mergeProps } from '@zag-js/svelte';

	const props: DatePickerTableBodyProps = $props();

	const datePicker = RootContext.consume();
	const viewProps = ViewContext.consume();

	const { element, children, ...rest } = $derived(props);

	const attributes = $derived(
		mergeProps(
			datePicker().getTableBodyProps(viewProps?.()),
			{
				class: classesDatePicker.tableBody,
			},
			rest,
		),
	);
</script>

{#if element}
	{@render element(attributes)}
{:else}
	<tbody {...attributes}>
		{@render children?.()}
	</tbody>
{/if}
