// packages/skeleton-svelte/src/components/qr-code/anatomy/frame.svelte
<script lang="ts" module>
	import type { HTMLAttributes } from '../../../internal/html-attributes.js';
	import type { PropsWithElement } from '../../../internal/props-with-element.js';

	export interface QrCodeFrameProps extends PropsWithElement<'svg'>, HTMLAttributes<'svg'> {}
</script>

<script lang="ts">
	import { RootContext } from '../modules/root-context.js';
	import { mergeProps } from '@zag-js/svelte';

	const props: QrCodeFrameProps = $props();

	const qrCode = RootContext.consume();

	const { element, children, ...rest } = $derived(props);

	const attributes = $derived(mergeProps(qrCode().getFrameProps(), rest));
</script>

{#if element}
	{@render element(attributes)}
{:else}
	<svg {...attributes}>
		{@render children?.()}
	</svg>
{/if}

// packages/skeleton-react/src/components/qr-code/anatomy/frame.tsx
import type { HTMLAttributes } from '../../../internal/html-attributes.js';
import type { PropsWithElement } from '../../../internal/props-with-element.js';
import { RootContext } from '../modules/root-context.js';
import { mergeProps } from '@zag-js/react';
import { use } from 'react';

export interface QrCodeFrameProps extends PropsWithElement<'svg'>, HTMLAttributes<'svg'> {}

export default function Frame(props: QrCodeFrameProps) {
	const qrCode = use(RootContext);

	const { element, children, ...rest } = props;

	const attributes = mergeProps(qrCode.getFrameProps(), rest);

	return element ? element(attributes) : <svg {...attributes}>{children}</svg>;
}
