// sites/skeleton.dev/src/examples/components/progress-linear/svelte/color.svelte
<script lang="ts">
	import { ProgressLinear } from '@skeletonlabs/skeleton-svelte';
</script>

<div class="flex w-full flex-col gap-8">
	<ProgressLinear>
		<ProgressLinear.Track>
			<ProgressLinear.Range class="bg-primary-500" />
		</ProgressLinear.Track>
	</ProgressLinear>
	<ProgressLinear>
		<ProgressLinear.Track>
			<ProgressLinear.Range class="bg-secondary-500" />
		</ProgressLinear.Track>
	</ProgressLinear>
	<ProgressLinear>
		<ProgressLinear.Track>
			<ProgressLinear.Range class="bg-tertiary-500" />
		</ProgressLinear.Track>
	</ProgressLinear>
</div>

// sites/skeleton.dev/src/examples/components/progress-linear/react/color.tsx
import { ProgressLinear } from '@skeletonlabs/skeleton-react';

export default function () {
	return (
		<div className="flex w-full flex-col gap-8">
			<ProgressLinear>
				<ProgressLinear.Track>
					<ProgressLinear.Range className="bg-primary-500" />
				</ProgressLinear.Track>
			</ProgressLinear>
			<ProgressLinear>
				<ProgressLinear.Track>
					<ProgressLinear.Range className="bg-secondary-500" />
				</ProgressLinear.Track>
			</ProgressLinear>
			<ProgressLinear>
				<ProgressLinear.Track>
					<ProgressLinear.Range className="bg-tertiary-500" />
				</ProgressLinear.Track>
			</ProgressLinear>
		</div>
	);
}
