// sites/skeleton.dev/src/examples/components/progress-linear/svelte/height.svelte
<script lang="ts">
	import { ProgressLinear } from '@skeletonlabs/skeleton-svelte';
</script>

<div class="flex w-full flex-col gap-8">
	<ProgressLinear>
		<ProgressLinear.Track class="h-1">
			<ProgressLinear.Range />
		</ProgressLinear.Track>
	</ProgressLinear>
	<ProgressLinear>
		<ProgressLinear.Track class="h-4">
			<ProgressLinear.Range />
		</ProgressLinear.Track>
	</ProgressLinear>
	<ProgressLinear>
		<ProgressLinear.Track class="h-6">
			<ProgressLinear.Range />
		</ProgressLinear.Track>
	</ProgressLinear>
</div>

// sites/skeleton.dev/src/examples/components/progress-linear/react/height.tsx
import { ProgressLinear } from '@skeletonlabs/skeleton-react';

export default function () {
	return (
		<div className="flex w-full flex-col gap-8">
			<ProgressLinear>
				<ProgressLinear.Track className="h-1">
					<ProgressLinear.Range />
				</ProgressLinear.Track>
			</ProgressLinear>
			<ProgressLinear>
				<ProgressLinear.Track className="h-4">
					<ProgressLinear.Range />
				</ProgressLinear.Track>
			</ProgressLinear>
			<ProgressLinear>
				<ProgressLinear.Track className="h-6">
					<ProgressLinear.Range />
				</ProgressLinear.Track>
			</ProgressLinear>
		</div>
	);
}
