// packages/skeleton-svelte/src/components/date-picker/anatomy/next-trigger.svelte
<script lang="ts" module>
	import type { HTMLAttributes } from '@/internal/html-attributes.js';
	import type { PropsWithElement } from '@/internal/props-with-element.js';

	export interface DatePickerNextTriggerProps extends PropsWithElement<'button'>, HTMLAttributes<'button'> {}
</script>

<script lang="ts">
	import { RootContext } from '../modules/root-context.js';
	import { ViewContext } from '../modules/view-context.js';
	import ChevronRightIcon from '@/internal/components/chevron-right.svelte';
	import { classesDatePicker } from '@skeletonlabs/skeleton-common';
	import { mergeProps } from '@zag-js/svelte';

	const props: DatePickerNextTriggerProps = $props();

	const datePicker = RootContext.consume();
	const viewProps = ViewContext.consume();

	const { element, children = chevronRight, ...rest } = $derived(props);

	const attributes = $derived(
		mergeProps(
			datePicker().getNextTriggerProps(viewProps()),
			{
				class: classesDatePicker.nextTrigger,
			},
			rest,
		),
	);
</script>

{#snippet chevronRight()}
	<ChevronRightIcon />
{/snippet}

{#if element}
	{@render element(attributes)}
{:else}
	<button {...attributes}>
		{@render children?.()}
	</button>
{/if}

// packages/skeleton-react/src/components/date-picker/anatomy/next-trigger.tsx
// oxlint-disable-next-line no-unused-vars
import { RootContext } from '../modules/root-context.js';
import { ViewContext } from '../modules/view-context';
import ChevronRight from '@/internal/components/chevron-right.js';
import type { HTMLAttributes } from '@/internal/html-attributes.js';
import type { PropsWithElement } from '@/internal/props-with-element.js';
import { classesDatePicker } from '@skeletonlabs/skeleton-common';
import { mergeProps } from '@zag-js/react';
import { use } from 'react';

export interface DatePickerNextTriggerProps extends PropsWithElement<'button'>, HTMLAttributes<'button'> {}

export default function NextTrigger(props: DatePickerNextTriggerProps) {
	const datePicker = use(RootContext);
	const viewProps = use(ViewContext);

	const { element, children = <ChevronRight />, ...rest } = props;

	const attributes = mergeProps(
		datePicker.getNextTriggerProps(viewProps),
		{
			className: classesDatePicker.nextTrigger,
		},
		rest,
	);

	return element ? element(attributes) : <button {...attributes}>{children}</button>;
}
