// packages/skeleton-svelte/src/components/date-picker/anatomy/range-text.svelte
<script lang="ts" module>
	import type { HTMLAttributes } from '@/internal/html-attributes';
	import type { PropsWithElement } from '@/internal/props-with-element';

	export interface DatePickerRangeTextProps extends PropsWithElement<'div'>, HTMLAttributes<'div'> {}
</script>

<script lang="ts">
	import { RootContext } from '../modules/root-context';
	import { classesDatePicker } from '@skeletonlabs/skeleton-common';
	import { mergeProps } from '@zag-js/svelte';

	const props: DatePickerRangeTextProps = $props();

	const datePicker = RootContext.consume();

	const rangeText = $derived(Array.from(new Set([datePicker().visibleRangeText.start, datePicker().visibleRangeText.end])).join(' - '));

	const { element, children = defaultChildren, ...rest } = $derived(props);

	const attributes = $derived(
		mergeProps(
			datePicker().getRangeTextProps(),
			{
				class: classesDatePicker.rangeText,
			},
			rest,
		),
	);
</script>

{#snippet defaultChildren()}
	{rangeText}
{/snippet}

{#if element}
	{@render element(attributes)}
{:else}
	<div {...attributes}>
		{@render children?.()}
	</div>
{/if}

// packages/skeleton-react/src/components/date-picker/anatomy/range-text.tsx
import { RootContext } from '../modules/root-context.js';
import type { HTMLAttributes } from '@/internal/html-attributes.js';
import type { PropsWithElement } from '@/internal/props-with-element.js';
import { classesDatePicker } from '@skeletonlabs/skeleton-common';
import { mergeProps } from '@zag-js/react';
import { use } from 'react';

export interface DatePickerRangeTextProps extends PropsWithElement<'div'>, HTMLAttributes<'div'> {}

export default function RangeText(props: DatePickerRangeTextProps) {
	const datePicker = use(RootContext);

	const rangeText = Array.from(new Set([datePicker.visibleRangeText.start, datePicker.visibleRangeText.end])).join(' - ');

	const { element, children = rangeText, ...rest } = props;

	const attributes = mergeProps(
		datePicker.getRangeTextProps(),
		{
			className: classesDatePicker.rangeText,
		},
		rest,
	);

	return element ? element(attributes) : <div {...attributes}>{children}</div>;
}
