// sites/next.skeleton.dev/src/examples/components/segment-control/ExampleDisableItem.svelte
<script lang="ts">
import { Segment } from "@skeletonlabs/skeleton-svelte";

let size = $state("sm");
</script>

<Segment name="size" value={size} onValueChange={(e) => (size = e.value)}>
  <Segment.Item value="sm">sm</Segment.Item>
  <Segment.Item value="md" disabled>md</Segment.Item>
  <Segment.Item value="lg">lg</Segment.Item>
</Segment>

// sites/next.skeleton.dev/src/examples/components/segment-control/ExampleDisableItem.tsx
import React, { useState } from 'react';
import { Segment } from '@skeletonlabs/skeleton-react';

export const Page: React.FC = () => {
	const [size, setSize] = useState('sm');

	return (
		<Segment name="size" value={size} onValueChange={setSize}>
			<Segment.Item value="sm">sm</Segment.Item>
			<Segment.Item value="md" disabled>
				md
			</Segment.Item>
			<Segment.Item value="lg">lg</Segment.Item>
		</Segment>
	);
};
