// sites/next.skeleton.dev/src/examples/components/switch/ExampleLightswitch.tsx
import React from 'react';
import { Switch } from '@skeletonlabs/skeleton-react';
import { Moon as IconMoon, Sun as IconSun } from 'lucide-react';

export const Page: React.FC = () => {
	// Bind to the checked state
	const [mode, setMode] = React.useState(false);

	// Handle the change in state when toggled.
	function handleModeChange(newValue: boolean) {
		// Update the bound state
		setMode(newValue);

		// NOTE: implementation may differ per Tailwind config and framework:
		// https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually
		console.log({ mode });
	}

	return (
		<Switch
			name="mode"
			controlActive="bg-surface-200"
			checked={mode}
			onCheckedChange={(e) => handleModeChange(e.checked)}
			inactiveChild={<IconMoon size="14" />}
			activeChild={<IconSun size="14" />}
		/>
	);
};

// sites/skeleton.dev/src/examples/components/switch/ExampleLightswitch.svelte
<script lang="ts">
	import { Switch } from '@skeletonlabs/skeleton-svelte';
	// Icons
	import IconMoon from '@lucide/svelte/icons/moon';
	import IconSun from '@lucide/svelte/icons/sun';

	// Bind to the checked state
	let mode = $state(false);

	// Handle the change in state when toggled.
	function handleModeChange(checked: boolean) {
		// NOTE: implementation may differ per Tailwind config and framework:
		// https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually
		console.log({ mode });
		mode = checked;
	}
</script>

<Switch name="mode" controlActive="bg-surface-200" checked={mode} onCheckedChange={(e) => handleModeChange(e.checked)}>
	{#snippet inactiveChild()}<IconMoon size="14" />{/snippet}
	{#snippet activeChild()}<IconSun size="14" />{/snippet}
</Switch>
