// packages/skeleton-react/src/components-overhaul/avatar/anatomy/avatar-image.tsx
'use client';

import { useContext } from 'react';
import { mergeProps } from '@zag-js/react';
import { AvatarRootContext } from '../modules/context.js';
import type { AvatarImageProps } from '../modules/types.js';

export default function (props: AvatarImageProps) {
	const rootContext = useContext(AvatarRootContext);
	const { child, ...restAttributes } = props;
	const attributes = mergeProps(
		rootContext.api.getImageProps(),
		{
			className: 'base:w-full base:object-cover'
		},
		restAttributes
	);
	return child ? child({ attributes }) : <img {...attributes} />;
}

// packages/skeleton-svelte/src/components-overhaul/avatar/anatomy/avatar-image.svelte
<script lang="ts">
	import { mergeProps } from '@zag-js/svelte';
	import { AvatarRootContext } from '../modules/context.js';
	import type { AvatarImageProps } from '../modules/types.js';

	const rootContext = AvatarRootContext.consume();
	const props: AvatarImageProps = $props();
	const { child, ...restAttributes } = $derived(props);
	const attributes = $derived(
		mergeProps(
			rootContext.api.getImageProps(),
			{
				class: 'base:w-full base:object-cover'
			},
			restAttributes
		)
	);
</script>

{#if child}
	{@render child(attributes)}
{:else}
	<img {...attributes} />
{/if}
