// packages/skeleton-svelte/src/components/switch/anatomy/control.svelte
<script lang="ts" module>
	import type { HTMLAttributes } from '@/internal/html-attributes';
	import type { PropsWithElement } from '@/internal/props-with-element';

	export interface SwitchControlProps extends PropsWithElement<'span'>, HTMLAttributes<'span'> {}
</script>

<script lang="ts">
	import { SwitchRootContext } from '../modules/root-context';
	import { classesSwitch } from '@skeletonlabs/skeleton-common';
	import { mergeProps } from '@zag-js/svelte';

	const props: SwitchControlProps = $props();

	const switch_ = SwitchRootContext.consume();

	const { element, children, ...rest } = $derived(props);

	const attributes = $derived(
		mergeProps(
			switch_().getControlProps(),
			{
				class: classesSwitch.control,
			},
			rest,
		),
	);
</script>

{#if element}
	{@render element(attributes)}
{:else}
	<span {...attributes}>
		{@render children?.()}
	</span>
{/if}

// packages/skeleton-react/src/components/switch/anatomy/control.tsx
import { useContext } from 'react';
import { mergeProps } from '@zag-js/react';
import { SwitchRootContext } from '../modules/root-context';
import { classesSwitch } from '@skeletonlabs/skeleton-common';
import type { PropsWithElement } from '@/internal/props-with-element';
import type { HTMLAttributes } from '@/internal/html-attributes';

export interface SwitchControlProps extends PropsWithElement<'span'>, HTMLAttributes<'span'> {}

export default function (props: SwitchControlProps) {
	const switch_ = useContext(SwitchRootContext);

	const { element, children, ...rest } = props;

	const attributes = mergeProps(switch_.getControlProps(), rest, {
		className: classesSwitch.control
	});

	return element ? element(attributes) : <span {...attributes}>{children}</span>;
}
