// packages/skeleton-react/src/components/progress/anatomy/circle-track.tsx
import type { HTMLAttributes } from '../../../internal/html-attributes.js';
import type { PropsWithElement } from '../../../internal/props-with-element.js';
import { RootContext } from '../modules/root-context.js';
import * as classes from '@skeletonlabs/skeleton-common/classes';
import { mergeProps } from '@zag-js/react';
import { use } from 'react';

export interface ProgressCircleTrackProps extends PropsWithElement<'circle'>, HTMLAttributes<'circle', 'children'> {}

export default function CircleTrack(props: ProgressCircleTrackProps) {
	const progress = use(RootContext);

	const { element, ...rest } = props;

	const attributes = mergeProps(
		progress.getCircleTrackProps(),
		{
			className: classes.progress.circleTrack,
		},
		rest,
	);

	return element ? element(attributes) : <circle {...attributes} />;
}

// packages/skeleton-svelte/src/components/progress/anatomy/circle-track.svelte
<script lang="ts" module>
	import type { HTMLAttributes } from '../../../internal/html-attributes.js';
	import type { PropsWithElement } from '../../../internal/props-with-element.js';

	export interface ProgressCircleTrackProps extends PropsWithElement<'circle'>, HTMLAttributes<'circle', 'children'> {}
</script>

<script lang="ts">
	import { RootContext } from '../modules/root-context.js';
	import * as classes from '@skeletonlabs/skeleton-common/classes';
	import { mergeProps } from '@zag-js/svelte';

	const props: ProgressCircleTrackProps = $props();

	const progress = RootContext.consume();

	const { element, ...rest } = $derived(props);

	const attributes = $derived(
		mergeProps(
			progress().getCircleTrackProps(),
			{
				class: classes.progress.circleTrack,
			},
			rest,
		),
	);
</script>

{#if element}
	{@render element(attributes)}
{:else}
	<circle {...attributes} />
{/if}
