// packages/skeleton-react/src/components/toggle-group/anatomy/item.tsx
import { RootContext } from '../modules/root-context';
import type { HTMLAttributes } from '@/internal/html-attributes';
import type { PropsWithElement } from '@/internal/props-with-element';
import { classesToggleGroup } from '@skeletonlabs/skeleton-common';
import { mergeProps } from '@zag-js/react';
import { splitItemProps, type ItemProps } from '@zag-js/toggle-group';
import { use } from 'react';

export interface ToggleGroupItemProps extends ItemProps, PropsWithElement<'button'>, HTMLAttributes<'button', 'value' | 'disabled'> {}

export default function Item(props: ToggleGroupItemProps) {
	const toggleGroup = use(RootContext);

	const [itemProps, componentProps] = splitItemProps(props);
	const { element, children, ...rest } = componentProps;

	const attributes = mergeProps(
		toggleGroup.getItemProps(itemProps),
		{
			className: classesToggleGroup.item,
		},
		rest,
	);

	return element ? element(attributes) : <button {...attributes}>{children}</button>;
}

// packages/skeleton-svelte/src/components/toggle-group/anatomy/item.svelte
<script lang="ts" module>
	import type { HTMLAttributes } from '@/internal/html-attributes';
	import type { PropsWithElement } from '@/internal/props-with-element';
	import type { ItemProps } from '@zag-js/toggle-group';

	export interface ToggleGroupItemProps extends ItemProps, PropsWithElement<'button'>, HTMLAttributes<'button', 'value' | 'disabled'> {}
</script>

<script lang="ts">
	import { RootContext } from '../modules/root-context';
	import { classesToggleGroup } from '@skeletonlabs/skeleton-common';
	import { mergeProps } from '@zag-js/svelte';
	import { splitItemProps } from '@zag-js/toggle-group';

	const props: ToggleGroupItemProps = $props();

	const toggleGroup = RootContext.consume();

	const [itemProps, componentProps] = $derived(splitItemProps(props));
	const { element, children, ...rest } = $derived(componentProps);

	const attributes = $derived(
		mergeProps(
			toggleGroup().getItemProps(itemProps),
			{
				class: classesToggleGroup.item,
			},
			rest,
		),
	);
</script>

{#if element}
	{@render element(attributes)}
{:else}
	<button {...attributes}>
		{@render children?.()}
	</button>
{/if}
