// packages/skeleton-react/src/components/rating-group/rating-group-root-context.tsx
import { useContext, type ReactNode } from 'react';
import type { Api } from '@zag-js/rating-group';
import { RatingGroupRootContext } from './rating-group-root-context.js';

export interface RatingGroupRootContextProps {
	children: (api: Api) => ReactNode;
}

export default function (props: RatingGroupRootContextProps) {
	const rootContext = useContext(RatingGroupRootContext);
	return props.children(rootContext.api);
}

// packages/skeleton-svelte/src/components/rating-group/rating-group-root-context.svelte
<script lang="ts" module>
	import type { Snippet } from 'svelte';
	import type { Api } from '@zag-js/rating-group';

	export interface RatingGroupRootContextProps {
		children: Snippet<[Api]>;
	}
</script>

<script lang="ts">
	import { RatingGroupRootContext } from './rating-group-root-context.js';

	const props: RatingGroupRootContextProps = $props();
	const rootContext = RatingGroupRootContext.consume();
</script>

{@render props.children(rootContext.api)}
