// packages/skeleton-react/src/components/progress-linear/anatomy/range.tsx
import { use } from 'react';
import { mergeProps } from '@zag-js/react';
import { classesProgressLinear } from '@skeletonlabs/skeleton-common';
import { ProgressLinearRootContext } from '../modules/root-context';
import type { PropsWithElement } from '@/internal/props-with-element';
import type { HTMLAttributes } from '@/internal/html-attributes';

export interface ProgressLinearRangeProps extends PropsWithElement<'div'>, HTMLAttributes<'div', 'children'> { }

export default function (props: ProgressLinearRangeProps) {
	const progressLinear = use(ProgressLinearRootContext);

	const { element, ...rest } = props;

	const attributes = mergeProps(progressLinear.getRangeProps(), rest, {
		className: classesProgressLinear.range
	});

	return element ? element(attributes) : <div {...attributes} />;
}

// packages/skeleton-svelte/src/components/progress-linear/anatomy/range.svelte
<script lang="ts" module>
	import type { HTMLAttributes } from '@/internal/html-attributes';
	import type { PropsWithElement } from '@/internal/props-with-element';

	export interface ProgressLinearRangeProps extends PropsWithElement<'div'>, HTMLAttributes<'div'> {}
</script>

<script lang="ts">
	import { ProgressLinearRootContext } from '../modules/root-context';
	import { classesProgressLinear } from '@skeletonlabs/skeleton-common';
	import { mergeProps } from '@zag-js/svelte';

	const props: ProgressLinearRangeProps = $props();

	const progressLinear = ProgressLinearRootContext.consume();

	const { element, children, ...rest } = $derived(props);

	const attributes = $derived(
		mergeProps(
			progressLinear().getRangeProps(),
			{
				class: classesProgressLinear.range,
			},
			rest,
		),
	);
</script>

{#if element}
	{@render element(attributes)}
{:else}
	<div {...attributes}>
		{@render children?.()}
	</div>
{/if}
