// sites/skeleton.dev/src/examples/components/progress-circular/svelte/format.svelte
<script lang="ts">
	import { Progress } from '@skeletonlabs/skeleton-svelte';
</script>

<Progress class="items-center w-fit" formatOptions={{ style: 'decimal' }}>
	<Progress.Circle --size="4rem" --thickness="0.5rem">
		<Progress.CircleTrack />
		<Progress.CircleRange />
	</Progress.Circle>
	<Progress.ValueText />
</Progress>

// sites/skeleton.dev/src/examples/components/progress-circular/react/format.tsx
import { Progress } from '@skeletonlabs/skeleton-react';

export default function Format() {
	return (
		<Progress className="items-center w-fit" formatOptions={{ style: 'decimal' }}>
			<Progress.Circle style={{ ['--size' as string]: '4rem', ['--thickness' as string]: '0.5rem' }}>
				<Progress.CircleTrack />
				<Progress.CircleRange />
			</Progress.Circle>
			<Progress.ValueText />
		</Progress>
	);
}
