// playgrounds/skeleton-svelte/src/routes/components/tooltip/+page.svelte
<script lang="ts">
	import { Tooltip } from '@skeletonlabs/skeleton-svelte';
</script>

<Tooltip>
	<Tooltip.Trigger>Trigger</Tooltip.Trigger>
	<Tooltip.Positioner>
		<Tooltip.Content>
			Content
			<Tooltip.Arrow>
				<Tooltip.ArrowTip />
			</Tooltip.Arrow>
		</Tooltip.Content>
	</Tooltip.Positioner>
</Tooltip>

// playgrounds/skeleton-react/src/app/components/tooltip/page.tsx
'use client';

import { Tooltip } from '@skeletonlabs/skeleton-react';

export default function () {
	return (
		<Tooltip>
			<Tooltip.Trigger>Trigger</Tooltip.Trigger>
			<Tooltip.Positioner>
				<Tooltip.Content>
					Content
					<Tooltip.Arrow>
						<Tooltip.ArrowTip />
					</Tooltip.Arrow>
				</Tooltip.Content>
			</Tooltip.Positioner>
		</Tooltip>
	);
}
