// packages/skeleton-svelte/src/components/popover/anatomy/popover-root-context.svelte
<script lang="ts" module>
	import type { Snippet } from 'svelte';
	import type { PopoverRootContextType } from '../modules/popover-root-context';

	export interface PopoverRootContextProps {
		children: Snippet<[PopoverRootContextType]>;
	}
</script>

<script lang="ts">
	import { PopoverRootContext } from '../modules/popover-root-context';

	const props: PopoverRootContextProps = $props();
	const rootContext = PopoverRootContext.consume();
</script>

{@render props.children(rootContext)}

// packages/skeleton-react/src/components/popover/anatomy/popover-root-context.tsx
import { useContext, type ReactNode } from 'react';
import { PopoverRootContext, type PopoverRootContextType } from '../modules/popover-root-context.js';

export interface PopoverRootContextProps {
	children: (context: PopoverRootContextType) => ReactNode;
}

export default function (props: PopoverRootContextProps) {
	const rootContext = useContext(PopoverRootContext);
	return props.children(rootContext);
}
