// packages/skeleton-svelte/src/routes/components/ratings/+page.svelte
<script lang="ts">
	import Rating from '$lib/components/Rating/Rating.svelte';
	import Star from 'lucide-svelte/icons/star';
	import Skull from 'lucide-svelte/icons/skull';
	import Bone from 'lucide-svelte/icons/bone';

	let interactiveValue = $state(3);
</script>

<div class="space-y-10">
	<header>
		<h1 class="h1">Ratings</h1>
	</header>

	<section class="space-y-4">
		<div class="flex items-center gap-8">
			<div class="w-48">
				<Rating value={5}>
					{#snippet iconFull()}
						<Star size={24} class="fill-surface-950-50" />
					{/snippet}
					{#snippet iconEmpty()}
						<Star size={24} />
					{/snippet}
				</Rating>
			</div>
			<h3 class="h3">5.0</h3>
		</div>
		<div class="flex items-center gap-8">
			<div class="w-48">
				<Rating value={0}>
					{#snippet iconFull()}
						<Star size={24} class="fill-surface-950-50" />
					{/snippet}
					{#snippet iconEmpty()}
						<Star size={24} />
					{/snippet}
				</Rating>
			</div>
			<h3 class="h3">0.0</h3>
		</div>
		<div class="flex items-center gap-8">
			<div class="w-48">
				<Rating value={2.5}>
					{#snippet iconFull()}
						<Star size={24} class="fill-surface-950-50" />
					{/snippet}
					{#snippet iconEmpty()}
						<Star size={24} />
					{/snippet}
				</Rating>
			</div>
			<h3 class="h3">2.5</h3>
		</div>
		<div class="flex items-center gap-8">
			<div class="w-48">
				<Rating value={3.75}>
					{#snippet iconFull()}
						<Star size={24} class="fill-surface-950-50" />
					{/snippet}
					{#snippet iconEmpty()}
						<Star size={24} />
					{/snippet}
				</Rating>
			</div>
			<h3 class="h3">3.75</h3>
		</div>
		<div class="flex items-center gap-8">
			<div class="w-48">
				<Rating value={1.25}>
					{#snippet iconFull()}
						<Star size={24} class="fill-surface-950-50" />
					{/snippet}
					{#snippet iconEmpty()}
						<Star size={24} />
					{/snippet}
				</Rating>
			</div>
			<h3 class="h3">1.25</h3>
		</div>
	</section>

	<section class="space-y-4">
		<h2 class="h2">Custom Icons</h2>
		<div class="flex items-center gap-8">
			<div class="w-48">
				<Rating bind:value={interactiveValue} interactive>
					{#snippet iconFull()}
						<Skull size={24} />
					{/snippet}
					{#snippet iconEmpty()}
						<Bone size={24} />
					{/snippet}
				</Rating>
			</div>
			<h3 class="h3">{interactiveValue.toFixed(2)}</h3>
		</div>
	</section>

	<section class="space-y-4">
		<h2 class="h2">interactive</h2>
		<div class="flex items-center gap-8">
			<div class="w-48">
				<Rating bind:value={interactiveValue} interactive onmousedown={(_, value) => console.log(`rating value: ${value}`)}>
					{#snippet iconFull()}
						<Star size={24} class="fill-surface-950-50" />
					{/snippet}
					{#snippet iconEmpty()}
						<Star size={24} />
					{/snippet}
				</Rating>
			</div>
			<h3 class="h3">{interactiveValue.toFixed(2)}</h3>
		</div>
	</section>

	<section class="space-y-4">
		<h2 class="h2">Steps</h2>
		<div class="flex items-center gap-8">
			<div class="w-48">
				<Rating bind:value={interactiveValue} interactive step={2}>
					{#snippet iconFull()}
						<Star size={24} class="fill-surface-950-50" />
					{/snippet}
					{#snippet iconEmpty()}
						<Star size={24} />
					{/snippet}
				</Rating>
			</div>
			<h3 class="h3">{interactiveValue.toFixed(2)}</h3>
		</div>
		<div class="flex items-center gap-8">
			<div class="w-48">
				<Rating bind:value={interactiveValue} interactive step={3}>
					{#snippet iconFull()}
						<Star size={24} class="fill-surface-950-50" />
					{/snippet}
					{#snippet iconEmpty()}
						<Star size={24} />
					{/snippet}
				</Rating>
			</div>
			<h3 class="h3">{interactiveValue.toFixed(2)}</h3>
		</div>
	</section>

	<section class="space-y-4">
		<h2 class="h2">RTL</h2>
		<div class="flex items-center gap-8">
			<div dir="rtl" class="w-48">
				<Rating bind:value={interactiveValue} interactive step={2}>
					{#snippet iconFull()}
						<Star size={24} class="fill-surface-950-50" />
					{/snippet}
					{#snippet iconEmpty()}
						<Star size={24} />
					{/snippet}
				</Rating>
			</div>
			<h3 class="h3">{interactiveValue.toFixed(2)}</h3>
		</div>
	</section>
</div>

// packages/skeleton-react/src/routes/components/ratings.tsx
import { useState } from 'react';
import { Rating } from '../../lib/components/Rating/Rating';
import { Bone, Skull, Star } from 'lucide-react';

function StaticRatings(value: number) {
	return (
		<div className="flex items-center gap-8">
			<div className="w-48">
				<Rating value={value} iconEmpty={<Star size={24} />} iconFull={<Star size={24} className="fill-surface-950-50" />} />
			</div>
			<h3 className="h3">{value}</h3>
		</div>
	);
}

function CustomIcons(value: number, setValue: React.Dispatch<React.SetStateAction<number>>) {
	return (
		<>
			<section className="space-y-4">
				<h2 className="h2">Custom Icons</h2>
				<div className="flex items-center gap-8">
					<div className="w-48">
						<Rating
							value={value}
							interactive
							onValueChange={(val) => setValue(val)}
							iconEmpty={<Bone size={24} />}
							iconFull={<Skull size={24} />}
						/>
					</div>
					<h3 className="h3">{value.toFixed(2)}</h3>
				</div>
			</section>
		</>
	);
}

function InteractiveRating(value: number, setValue: React.Dispatch<React.SetStateAction<number>>) {
	return (
		<>
			<section className="space-y-4">
				<h2 className="h2">Interactive</h2>
				<div className="flex items-center gap-8">
					<div className="w-48">
						<Rating
							value={value}
							interactive
							onValueChange={(val) => setValue(val)}
							iconEmpty={<Star size={24} />}
							iconFull={<Star size={24} className="fill-surface-950-50" />}
						/>
					</div>
					<h3 className="h3">{value.toFixed(2)}</h3>
				</div>
			</section>
		</>
	);
}

function Steps(step: number, value: number, setValue: React.Dispatch<React.SetStateAction<number>>) {
	return (
		<>
			<div className="flex items-center gap-8">
				<div className="w-48">
					<Rating
						value={value}
						step={step}
						interactive
						onValueChange={(val) => setValue(val)}
						iconEmpty={<Star size={24} />}
						iconFull={<Star size={24} className="fill-surface-950-50" />}
					/>
				</div>
				<h3 className="h3">{value.toFixed(2)}</h3>
			</div>
		</>
	);
}

function RTL(value: number, setValue: React.Dispatch<React.SetStateAction<number>>) {
	return (
		<>
			<section className="space-y-4">
				<h2 className="h2">RTL</h2>
				<div className="flex items-center gap-8">
					<div className="w-48" dir="rtl">
						<Rating
							value={value}
							step={2}
							interactive
							onValueChange={(val) => setValue(val)}
							iconEmpty={<Star size={24} />}
							iconFull={<Star size={24} className="fill-surface-950-50" />}
						/>
					</div>
					<h3 className="h3">{value.toFixed(2)}</h3>
				</div>
			</section>
		</>
	);
}

export function Component() {
	const [interactiveValue, setInteractiveValue] = useState(3);
	return (
		<>
			<div className="space-y-10">
				<header>
					<h1 className="h1">Ratings</h1>
				</header>

				<section className="space-y-4">
					{StaticRatings(5)}
					{StaticRatings(0)}
					{StaticRatings(2.5)}
					{StaticRatings(3.75)}
					{StaticRatings(1.25)}
				</section>

				{CustomIcons(interactiveValue, setInteractiveValue)}
				{InteractiveRating(interactiveValue, setInteractiveValue)}

				<section className="space-y-4">
					<h2 className="h2">Steps</h2>
					{Steps(2, interactiveValue, setInteractiveValue)}
					{Steps(3, interactiveValue, setInteractiveValue)}
				</section>

				{RTL(interactiveValue, setInteractiveValue)}
			</div>
		</>
	);
}
