// packages/skeleton-svelte/src/components/combobox/anatomy/combobox-item.svelte
<script lang="ts" module>
	import type { PropsWithElement } from '@/internal/props-with-element';
	import type { HTMLLiAttributes } from 'svelte/elements';
	import type { ItemProps } from '@zag-js/combobox';

	export interface ComboboxItemProps extends PropsWithElement, Omit<ItemProps, 'id'>, Omit<HTMLLiAttributes, 'value'> {}
</script>

<script lang="ts">
	import { mergeProps } from '@zag-js/svelte';
	import { classesCombobox } from '@skeletonlabs/skeleton-common';
	import { ComboboxRootContext } from '../modules/combobox-root-context';
	import { splitItemProps } from '@zag-js/combobox';
	import { ComboboxItemContext } from '../modules/combobox-item-context';

	const props: ComboboxItemProps = $props();
	const rootContext = ComboboxRootContext.consume();
	const [itemProps, componentProps] = $derived(splitItemProps(props));
	const { element, children, ...restAttributes } = $derived(componentProps);
	const attributes = $derived(mergeProps(rootContext.api.getItemProps(itemProps), { class: classesCombobox.item }, restAttributes));
	ComboboxItemContext.provide({
		get itemState() {
			return rootContext.api.getItemState(itemProps);
		}
	});
</script>

{#if element}
	{@render element({ attributes })}
{:else}
	<li {...attributes}>
		{@render children?.()}
	</li>
{/if}

// packages/skeleton-react/src/components/combobox/anatomy/combobox-item.tsx
import { useContext, type ComponentProps } from 'react';
import { mergeProps } from '@zag-js/react';
import { ComboboxRootContext } from '../modules/combobox-root-context';
import { classesCombobox } from '@skeletonlabs/skeleton-common';
import { splitItemProps, type ItemProps } from '@zag-js/combobox';
import type { PropsWithElement } from '@/internal/props-with-element';
import { ComboboxItemContext } from '../modules/combobox-item-context';

export interface ComboboxItemProps extends PropsWithElement, ItemProps, ComponentProps<'li'> {}

export default function (props: ComboboxItemProps) {
	const rootContext = useContext(ComboboxRootContext);
	const [itemProps, componentProps] = splitItemProps(props);
	const { element, children, ...restAttributes } = componentProps;
	const attributes = mergeProps(rootContext.api.getItemProps(itemProps), { className: classesCombobox.item }, restAttributes);
	return (
		<ComboboxItemContext.Provider value={{ itemState: rootContext.api.getItemState(itemProps) }}>
			{element ? element({ attributes }) : <li {...attributes}>{children}</li>}
		</ComboboxItemContext.Provider>
	);
}
