// packages/skeleton-svelte/src/components/combobox/anatomy/combobox-item-context.svelte
<script lang="ts" module>
	import type { Snippet } from 'svelte';
	import type { ComboboxItemContextType } from '../modules/combobox-item-context';

	export interface ComboboxItemContextProps {
		children: Snippet<[ComboboxItemContextType]>;
	}
</script>

<script lang="ts">
	import { ComboboxItemContext } from '../modules/combobox-item-context';

	const props: ComboboxItemContextProps = $props();
	const itemContext = ComboboxItemContext.consume();
</script>

{@render props.children(itemContext)}

// packages/skeleton-react/src/components/combobox/anatomy/combobox-item-context.tsx
import { useContext, type ReactNode } from 'react';
import { ComboboxItemContext, type ComboboxItemContextType } from '../modules/combobox-item-context';

export interface ComboboxItemContextProps {
	children: (context: ComboboxItemContextType) => ReactNode;
}

export default function (props: ComboboxItemContextProps) {
	const itemContext = useContext(ComboboxItemContext);
	return props.children(itemContext);
}
