// packages/skeleton-svelte/src/components/combobox/anatomy/item-group-context.svelte
<script lang="ts" module>
	import type { Snippet } from 'svelte';
	import type { ComboboxItemGroupContextType } from '../modules/item-group-context';

	export interface ComboboxItemGroupContextProps {
		children: Snippet<[ComboboxItemGroupContextType]>;
	}
</script>

<script lang="ts">
	import { ComboboxItemGroupContext } from '../modules/item-group-context';

	const props: ComboboxItemGroupContextProps = $props();
	const itemgroupContext = ComboboxItemGroupContext.consume();
</script>

{@render props.children(itemgroupContext)}

// packages/skeleton-react/src/components/combobox/anatomy/item-group-context.ts
import { useContext, type ReactNode } from 'react';
import { ComboboxItemGroupContext, type ComboboxItemGroupContextType } from '../modules/item-group-context';

export interface ComboboxItemGroupContextProps {
	children: (context: ComboboxItemGroupContextType) => ReactNode;
}

export default function (props: ComboboxItemGroupContextProps) {
	const itemGroupContext = useContext(ComboboxItemGroupContext);
	return props.children(itemGroupContext);
}
