// sites/next.skeleton.dev/src/examples/components/tabs/ExampleFluid.svelte
<script lang="ts">
import { Tabs } from "@skeletonlabs/skeleton-svelte";

let group = $state("plane");
const lorem =
	"Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nostrum veniam reprehenderit eum, reiciendis obcaecati, excepturi nemo ipsa fugit suscipit autem vitae numquam et cumque praesentium vero eos minus itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nostrum veniam reprehenderit eum, reiciendis obcaecati, excepturi nemo.";
</script>

<Tabs value={group} onValueChange={(e) => (group = e.value)} fluid>
  {#snippet list()}
    <Tabs.Control value="plane">Plane</Tabs.Control>
    <Tabs.Control value="boat">Boat</Tabs.Control>
    <Tabs.Control value="car">Car</Tabs.Control>
  {/snippet}
  {#snippet content()}
    <Tabs.Panel value="plane">Plane Panel - {lorem}</Tabs.Panel>
    <Tabs.Panel value="boat">Boat Panel - {lorem}</Tabs.Panel>
    <Tabs.Panel value="car">Car Panel - {lorem}</Tabs.Panel>
  {/snippet}
</Tabs>

// sites/next.skeleton.dev/src/examples/components/tabs/ExampleFluid.tsx
import React, { useState } from 'react';
import { Tabs } from '@skeletonlabs/skeleton-react';

export const Page: React.FC = () => {
	const [group, setGroup] = useState('plane');
	const lorem =
		'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nostrum veniam reprehenderit eum, reiciendis obcaecati, excepturi nemo ipsa fugit suscipit autem vitae numquam et cumque praesentium vero eos minus itaque. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nostrum veniam reprehenderit eum, reiciendis obcaecati, excepturi nemo.';
	return (
		<Tabs value={group} onValueChange={setGroup} fluid>
			<Tabs.List>
				<Tabs.Control value="plane">Plane</Tabs.Control>
				<Tabs.Control value="boat">Boat</Tabs.Control>
				<Tabs.Control value="car">Car</Tabs.Control>
			</Tabs.List>
			<Tabs.Content>
				<Tabs.Panel value="plane">Plane Panel - {lorem}</Tabs.Panel>
				<Tabs.Panel value="boat">Boat Panel - {lorem}</Tabs.Panel>
				<Tabs.Panel value="car">Car Panel - {lorem}</Tabs.Panel>
			</Tabs.Content>
		</Tabs>
	);
};
