// packages/skeleton-svelte/src/components/accordion/accordion-root-context.svelte
<script lang="ts" module>
	import type { Api } from '@zag-js/accordion';
	import type { Snippet } from 'svelte';

	export interface AccordionRootContextProps {
		children: Snippet<[Api]>;
	}
</script>

<script lang="ts">
	import { AccordionRootContext } from './accordion-root.context.js';

	const props: AccordionRootContextProps = $props();
	const rootContext = AccordionRootContext.consume();
</script>

{@render props.children(rootContext.api)}

// packages/skeleton-react/src/components/accordion/accordion-root-context.tsx
import { useContext, type ReactNode } from 'react';
import { AccordionRootContext } from './accordion-root.context';
import type { Api } from '@zag-js/accordion';

export interface AccordionRootContextProps {
	children: (api: Api) => ReactNode;
}

export default function (props: AccordionRootContextProps) {
	const rootContext = useContext(AccordionRootContext);
	return props.children(rootContext.api);
}
