// packages/skeleton-svelte/src/components/accordion/accordion-item.svelte
<script lang="ts" module>
	import type { HTMLAttributes } from 'svelte/elements';
	import type { PropsWithElement } from '../../internal/props-with-element.js';
	import type { ItemProps } from '@zag-js/accordion';

	interface AccordionItemProps extends PropsWithElement, ItemProps, HTMLAttributes<HTMLDivElement> {}

	export type { AccordionItemProps };
</script>

<script lang="ts">
	import { mergeProps } from '@zag-js/svelte';
	import { splitItemProps } from '@zag-js/accordion';
	import { classesAccordion } from '@skeletonlabs/skeleton-common';
	import { AccordionItemContext } from './accordion-item-context.js';
	import { AccordionRootContext } from './accordion-root-context.js';

	const rootContext = AccordionRootContext.consume();
	const props: AccordionItemProps = $props();
	const [itemProps, componentProps] = $derived(splitItemProps(props));
	const { element, children, ...restAttributes } = $derived(componentProps);
	const attributes = $derived(
		mergeProps(
			rootContext.api.getItemProps(itemProps),
			{
				class: classesAccordion.item
			},
			restAttributes
		)
	);
	AccordionItemContext.provide({
		get itemProps() {
			return itemProps;
		},
		get itemState() {
			return rootContext.api.getItemState(itemProps);
		}
	});
</script>

{#if element}
	{@render element({ attributes })}
{:else}
	<div {...attributes}>
		{@render children?.()}
	</div>
{/if}

// packages/skeleton-react/src/components/accordion/accordion-item.tsx
import { useContext, type ComponentProps, type PropsWithChildren } from 'react';
import { splitItemProps, type ItemProps } from '@zag-js/accordion';
import { mergeProps } from '@zag-js/react';
import { classesAccordion } from '@skeletonlabs/skeleton-common';
import { AccordionRootContext } from './accordion-root-context.js';
import { AccordionItemContext } from './accordion-item-context.js';
import type { PropsWithElement } from '../../internal/props-with-element.js';

export interface AccordionItemProps extends PropsWithChildren, PropsWithElement, ItemProps, ComponentProps<'div'> {}

export default function (props: AccordionItemProps) {
	const rootContext = useContext(AccordionRootContext);
	const [itemProps, componentProps] = splitItemProps(props);
	const { element, children, ...restAttributes } = componentProps;
	const attributes = mergeProps(
		rootContext.api.getItemProps(itemProps),
		{
			className: classesAccordion.item
		},
		restAttributes
	);
	return (
		<AccordionItemContext.Provider value={{ itemProps, itemState: rootContext.api.getItemState(itemProps) }}>
			{element ? element({ attributes }) : <div {...attributes}>{children}</div>}
		</AccordionItemContext.Provider>
	);
}
