// packages/skeleton-react/src/components/accordion/anatomy/accordion-content.tsx
import { useContext, type ComponentProps, type PropsWithChildren } from 'react';
import { mergeProps } from '@zag-js/react';
import { classesAccordion } from '@skeletonlabs/skeleton-common';
import { AccordionRootContext } from '../modules/accordion-root-context';
import { AccordionItemContext } from '../modules/accordion-item-context';
import type { PropsWithElement } from '@/internal/props-with-element';

export interface AccordionContentProps extends PropsWithChildren, PropsWithElement, ComponentProps<'div'> {}

export default function (props: AccordionContentProps) {
	const rootContext = useContext(AccordionRootContext);
	const itemContext = useContext(AccordionItemContext);
	const { element, children, ...restAttributes } = props;
	const attributes = mergeProps(
		rootContext.api.getItemContentProps(itemContext.itemProps),
		{
			className: classesAccordion.content
		},
		restAttributes
	);
	return element ? element({ attributes }) : <div {...attributes}>{children}</div>;
}

// packages/skeleton-svelte/src/components/accordion/accordion-content.svelte
<script lang="ts" module>
	import type { HTMLAttributes } from 'svelte/elements';
	import type { PropsWithElement } from '../../internal/props-with-element.js';
	interface AccordionContentProps extends PropsWithElement, HTMLAttributes<HTMLDivElement> {}

	export type { AccordionContentProps };
</script>

<script lang="ts">
	import { mergeProps } from '@zag-js/svelte';
	import { classesAccordion } from '@skeletonlabs/skeleton-common';
	import { AccordionRootContext } from './accordion-root-context.js';
	import { AccordionItemContext } from './accordion-item-context.js';

	const rootContext = AccordionRootContext.consume();
	const itemContext = AccordionItemContext.consume();
	const props: AccordionContentProps = $props();
	const { element, children, ...restAttributes } = $derived(props);
	const attributes = $derived(
		mergeProps(
			rootContext.api.getItemContentProps(itemContext.itemProps),
			{
				class: classesAccordion.content
			},
			restAttributes
		)
	);
</script>

{#if element}
	{@render element({ attributes })}
{:else}
	<div {...attributes}>
		{@render children?.()}
	</div>
{/if}
