// playgrounds/skeleton-react/src/routes/components/file-upload/index.tsx
'use client';

import { FileUpload, useFileUpload } from '@skeletonlabs/skeleton-react';
import { createFileRoute } from '@tanstack/react-router';
import { CircleXIcon } from 'lucide-react';

export const Route = createFileRoute('/components/file-upload/')({
	component: Page,
});

function Page() {
	const fileUpload = useFileUpload();

	return (
		<>
			<FileUpload.Provider value={fileUpload}>
				<FileUpload.Label>Upload your files</FileUpload.Label>
				<FileUpload.Dropzone>
					<FileUpload.Trigger>Browse Files</FileUpload.Trigger>
					<FileUpload.HiddenInput />
				</FileUpload.Dropzone>
				<FileUpload.ItemGroup>
					<FileUpload.Context>
						{(fileUpload) =>
							fileUpload.acceptedFiles.map((file) => (
								<FileUpload.Item key={file.name} file={file}>
									<FileUpload.ItemName>{file.name}</FileUpload.ItemName>
									<FileUpload.ItemSizeText>{file.size} bytes</FileUpload.ItemSizeText>
									<FileUpload.ItemDeleteTrigger>
										<CircleXIcon />
									</FileUpload.ItemDeleteTrigger>
								</FileUpload.Item>
							))
						}
					</FileUpload.Context>
				</FileUpload.ItemGroup>
			</FileUpload.Provider>
			<button className="btn preset-outlined-error-500" onClick={() => fileUpload.clearFiles()}>
				Clear Files
			</button>
		</>
	);
}

// playgrounds/skeleton-svelte/src/routes/components/file-upload/+page.svelte
<script lang="ts">
	import { FileUpload, useFileUpload } from '@skeletonlabs/skeleton-svelte';
	import X from '@lucide/svelte/icons/x';

	const id = $props.id();
	const fileUpload = useFileUpload({ id, disabled: true });
</script>

<FileUpload.Provider value={fileUpload}>
	<FileUpload.Dropzone>
		<FileUpload.Trigger>Upload</FileUpload.Trigger>
		<FileUpload.HiddenInput />
	</FileUpload.Dropzone>
	<FileUpload.ItemGroup>
		<FileUpload.Context>
			{#snippet children(fileUpload)}
				{#each fileUpload().acceptedFiles as file (file.name)}
					<FileUpload.Item {file}>
						<FileUpload.ItemName>{file.name}</FileUpload.ItemName>
						<FileUpload.ItemSizeText>{file.size} bytes</FileUpload.ItemSizeText>
						<FileUpload.ItemDeleteTrigger><X /></FileUpload.ItemDeleteTrigger>
					</FileUpload.Item>
				{/each}
			{/snippet}
		</FileUpload.Context>
	</FileUpload.ItemGroup>
</FileUpload.Provider>

<button class="btn preset-outlined-error-500" onclick={() => fileUpload().clearFiles()}> Clear Files </button>
