// playgrounds/skeleton-svelte/src/routes/components/tree-view/+page.svelte
<script lang="ts">
	import { TreeView, createTreeViewCollection, type TreeViewNodeProps } from '@skeletonlabs/skeleton-svelte';

	interface Node {
		id: string;
		name: string;
		children?: Node[];
	}

	const collection = createTreeViewCollection<Node>({
		nodeToValue: (node) => node.id,
		nodeToString: (node) => node.name,
		rootNode: {
			id: 'ROOT',
			name: '',
			children: [
				{
					id: 'node_modules',
					name: 'node_modules',
					children: [
						{ id: 'node_modules/zag-js', name: 'zag-js' },
						{ id: 'node_modules/pandacss', name: 'panda' },
						{
							id: 'node_modules/@types',
							name: '@types',
							children: [
								{ id: 'node_modules/@types/react', name: 'react' },
								{ id: 'node_modules/@types/react-dom', name: 'react-dom' }
							]
						}
					]
				}
			]
		}
	});
</script>

{#snippet treeNode(nodeProps: TreeViewNodeProps)}
	{@const { node, indexPath } = nodeProps}
	<TreeView.RootContext>
		{#snippet children({ api })}
			{#if api.getNodeState(nodeProps).isBranch}
				<TreeView.Branch {nodeProps}>
					<TreeView.BranchIndicator />
					<TreeView.BranchControl>
						<TreeView.BranchText>{node.name}</TreeView.BranchText>
					</TreeView.BranchControl>
					<TreeView.BranchContent>
						<TreeView.BranchIndentGuide />
						{#each node.children as childNode, childIndex (childIndex)}
							{@render treeNode({ indexPath: [...indexPath, childIndex], node: childNode })}
						{/each}
					</TreeView.BranchContent>
				</TreeView.Branch>
			{:else}
				<TreeView.Item {nodeProps}>
					{node.name}
				</TreeView.Item>
			{/if}
		{/snippet}
	</TreeView.RootContext>
{/snippet}

<TreeView {collection}>
	<TreeView.Label>File System</TreeView.Label>
	<TreeView.Tree>
		{#each collection.rootNode.children || [] as node, index (index)}
			{@render treeNode({ indexPath: [index], node })}
		{/each}
	</TreeView.Tree>
</TreeView>

// playgrounds/skeleton-react/src/app/components/tree-view/page.tsx
'use client';

import { TreeView, createTreeViewCollection } from '@skeletonlabs/skeleton-react';
import { ChevronDownIcon, FileIcon, FolderIcon } from 'lucide-react';

interface Node {
	id: string;
	name: string;
	children?: Node[];
}

function TreeNode(props: { node: Node; indexPath: number[] }) {
	return (
		<TreeView.NodeProvider value={props}>
			{props.node.children ? (
				<TreeView.Branch>
					<TreeView.BranchControl>
						<TreeView.BranchIndicator>
							<ChevronDownIcon />
						</TreeView.BranchIndicator>
						<TreeView.BranchText>
							<FolderIcon />
							{props.node.name}
						</TreeView.BranchText>
					</TreeView.BranchControl>
					<TreeView.BranchContent>
						<TreeView.BranchIndentGuide />
						{props.node.children.map((childNode, childIndex) => (
							<TreeNode key={childNode.id} node={childNode} indexPath={[...props.indexPath, childIndex]} />
						))}
					</TreeView.BranchContent>
				</TreeView.Branch>
			) : (
				<TreeView.Item>
					<FileIcon />
					{props.node.name}
				</TreeView.Item>
			)}
		</TreeView.NodeProvider>
	);
}

export default function Page() {
	const collection = createTreeViewCollection<Node>({
		nodeToValue: (node) => node.id,
		nodeToString: (node) => node.name,
		rootNode: {
			id: 'root',
			name: '',
			children: [
				{
					id: 'node_modules',
					name: 'node_modules',
					children: [
						{
							id: 'node_modules/@types',
							name: '@types',
							children: [
								{
									id: 'node_modules/@types/react',
									name: 'react',
								},
								{
									id: 'node_modules/@types/react-dom',
									name: 'react-dom',
								},
							],
						},
						{
							id: 'node_modules/zag-js',
							name: 'zag-js',
						},
						{
							id: 'node_modules/pandacss',
							name: 'panda',
						},
					],
				},
				{
					id: 'package.json',
					name: 'package.json',
				},
			],
		},
	});
	return (
		<TreeView collection={collection}>
			<TreeView.Label>File System</TreeView.Label>
			<TreeView.Tree>
				{collection.rootNode.children?.map((node, index) => (
					<TreeNode node={node} indexPath={[index]} key={node.id} />
				))}
			</TreeView.Tree>
		</TreeView>
	);
}
