// packages/skeleton-svelte/src/components/progress-circular/anatomy/track.svelte
<script lang="ts" module>
	import type { HTMLAttributes } from '@/internal/html-attributes';
	import type { PropsWithElement } from '@/internal/props-with-element';

	export interface ProgressCircularTrackProps extends PropsWithElement<'circle'>, HTMLAttributes<'circle', 'children'> {}
</script>

<script lang="ts">
	import { RootContext } from '../modules/root-context';
	import { classesProgressCircular } from '@skeletonlabs/skeleton-common';
	import { mergeProps } from '@zag-js/svelte';

	const props: ProgressCircularTrackProps = $props();

	const progressCircular = RootContext.consume();

	const { element, ...rest } = $derived(props);

	const attributes = $derived(
		mergeProps(
			progressCircular().getCircleTrackProps(),
			{
				class: classesProgressCircular.track,
			},
			rest,
		),
	);
</script>

{#if element}
	{@render element(attributes)}
{:else}
	<circle {...attributes} />
{/if}

// packages/skeleton-react/src/components/progress-circular/anatomy/track.tsx
import { RootContext } from '../modules/root-context';
import type { HTMLAttributes } from '@/internal/html-attributes';
import type { PropsWithElement } from '@/internal/props-with-element';
import { classesProgressCircular } from '@skeletonlabs/skeleton-common';
import { mergeProps } from '@zag-js/react';
import { use } from 'react';

export interface ProgressCircularTrackProps extends PropsWithElement<'circle'>, HTMLAttributes<'circle', 'children'> {}

export default function Track(props: ProgressCircularTrackProps) {
	const progressCircular = use(RootContext);

	const { element, ...rest } = props;

	const attributes = mergeProps(
		progressCircular.getCircleTrackProps(),
		{
			className: classesProgressCircular.track,
		},
		rest,
	);

	return element ? element(attributes) : <circle {...attributes} />;
}
