// packages/skeleton-svelte/src/components/dialog/anatomy/dialog-trigger.svelte
<script lang="ts" module>
	import type { PropsWithElement } from '@/internal/props-with-element';
	import type { HTMLButtonAttributes } from 'svelte/elements';

	export interface DialogTriggerProps extends PropsWithElement, HTMLButtonAttributes {}
</script>

<script lang="ts">
	import { mergeProps } from '@zag-js/svelte';
	import { classesDialog } from '@skeletonlabs/skeleton-common';
	import { DialogRootContext } from '../modules/dialog-root-context';

	const props: DialogTriggerProps = $props();
	const rootContext = DialogRootContext.consume();
	const { element, children, ...restAttributes } = $derived(props);
	const attributes = $derived(mergeProps(rootContext.api.getTriggerProps(), { class: classesDialog.trigger }, restAttributes));
</script>

{#if element}
	{@render element({ attributes })}
{:else}
	<button {...attributes}>
		{@render children?.()}
	</button>
{/if}

// packages/skeleton-react/src/components/dialog/anatomy/dialog-trigger.tsx
import { useContext, type ComponentProps } from 'react';
import { mergeProps } from '@zag-js/react';
import { DialogRootContext } from '../modules/dialog-root-context';
import { classesDialog } from '@skeletonlabs/skeleton-common';
import type { PropsWithElement } from '@/internal/props-with-element';

export interface DialogTriggerProps extends PropsWithElement, ComponentProps<'button'> {}

export default function (props: DialogTriggerProps) {
	const rootContext = useContext(DialogRootContext);
	const { element, children, ...restAttributes } = props;
	const attributes = mergeProps(rootContext.api.getTriggerProps(), { className: classesDialog.trigger }, restAttributes);
	return element ? element({ attributes }) : <button {...attributes}>{children}</button>;
}
