// packages/skeleton-svelte/src/components/dialog/anatomy/dialog-root.svelte
<script lang="ts" module>
	import type { PropsWithChildren } from '@/internal/props-with-children';
	import type { Props } from '@zag-js/dialog';

	export interface DialogRootProps extends PropsWithChildren, Omit<Props, 'id'> {}
</script>

<script lang="ts">
	import { useMachine, normalizeProps } from '@zag-js/svelte';
	import { DialogRootContext } from '../modules/dialog-root-context';
	import { connect, machine, splitProps } from '@zag-js/dialog';

	const props: DialogRootProps = $props();
	const [machineProps, componentProps] = $derived(splitProps(props));
	const { children } = $derived(componentProps);
	const id = $props.id();
	const service = useMachine(machine, () => ({
		id: id,
		...machineProps
	}));
	const api = $derived(connect(service, normalizeProps));
	DialogRootContext.provide({
		get api() {
			return api;
		}
	});
</script>

{@render children?.()}

// packages/skeleton-react/src/components/dialog/anatomy/dialog-root.tsx
import { useId, type PropsWithChildren } from 'react';
import { useMachine, normalizeProps } from '@zag-js/react';
import { splitProps, machine, connect, type Props } from '@zag-js/dialog';
import { DialogRootContext } from '../modules/dialog-root-context';

export interface DialogRootProps extends PropsWithChildren, Omit<Props, 'id'> {}

export default function (props: DialogRootProps) {
	const [machineProps, componentProps] = splitProps(props);
	const { children } = componentProps;
	const service = useMachine(machine, {
		id: useId(),
		...machineProps
	});
	const api = connect(service, normalizeProps);
	return <DialogRootContext.Provider value={{ api }}>{children}</DialogRootContext.Provider>;
}
