// packages/skeleton-react/src/components/qr-code/anatomy/overlay.tsx
import type { HTMLAttributes } from '../../../internal/html-attributes.js';
import type { PropsWithElement } from '../../../internal/props-with-element.js';
import { QrCodeRootContext } from '../modules/root-context.js';
import { mergeProps } from '@zag-js/react';
import { use } from 'react';

export interface QrCodeOverlayProps extends PropsWithElement<'div'>, HTMLAttributes<'div'> {}

export default function Overlay(props: QrCodeOverlayProps) {
	const qrCode = use(QrCodeRootContext);

	const { element, children, ...rest } = props;

	const attributes = mergeProps(qrCode.getOverlayProps(), rest);

	return element ? element(attributes) : <div {...attributes}>{children}</div>;
}

// packages/skeleton-svelte/src/components/qr-code/anatomy/overlay.svelte
<script lang="ts" module>
	import type { HTMLAttributes } from '../../../internal/html-attributes.js';
	import type { PropsWithElement } from '../../../internal/props-with-element.js';

	export interface QrCodeOverlayProps extends PropsWithElement<'div'>, HTMLAttributes<'div'> {}
</script>

<script lang="ts">
	import { QrCodeRootContext } from '../modules/root-context.js';
	import { mergeProps } from '@zag-js/svelte';

	const props: QrCodeOverlayProps = $props();

	const qrCode = QrCodeRootContext.consume();

	const { element, children, ...rest } = $derived(props);

	const attributes = $derived(mergeProps(qrCode().getOverlayProps(), rest));
</script>

{#if element}
	{@render element(attributes)}
{:else}
	<div {...attributes}>
		{@render children?.()}
	</div>
{/if}
