// packages/skeleton-react/src/components/qr-code/anatomy/root-provider.tsx
import type { HTMLAttributes } from '../../../internal/html-attributes.js';
import type { PropsWithElement } from '../../../internal/props-with-element.js';
import type { useQrCode } from '../modules/provider.js';
import { RootContext } from '../modules/root-context.js';
import { mergeProps } from '@zag-js/react';

export interface QrCodeRootProviderProps extends PropsWithElement<'div'>, HTMLAttributes<'div', 'id' | 'dir'> {
	value: ReturnType<typeof useQrCode>;
}

export default function RootProvider(props: QrCodeRootProviderProps) {
	const { element, children, value: qrCode, ...rest } = props;

	const attributes = mergeProps(qrCode.getRootProps(), rest);

	return (
		<RootContext.Provider value={qrCode}>{element ? element(attributes) : <div {...attributes}>{children}</div>}</RootContext.Provider>
	);
}

// packages/skeleton-svelte/src/components/qr-code/anatomy/root-provider.svelte
<script lang="ts" module>
	import type { HTMLAttributes } from '../../../internal/html-attributes.js';
	import type { PropsWithElement } from '../../../internal/props-with-element.js';
	import type { useQrCode } from '../modules/provider.svelte';

	export interface QrCodeRootProviderProps extends PropsWithElement<'div'>, HTMLAttributes<'div', 'id' | 'dir'> {
		value: ReturnType<typeof useQrCode>;
	}
</script>

<script lang="ts">
	import { RootContext } from '../modules/root-context.js';
	import { mergeProps } from '@zag-js/svelte';

	const props: QrCodeRootProviderProps = $props();

	const { element, children, value: qrCode, ...rest } = $derived(props);

	const attributes = $derived(mergeProps(qrCode().getRootProps(), rest));

	RootContext.provide(() => qrCode());
</script>

{#if element}
	{@render element(attributes)}
{:else}
	<div {...attributes}>
		{@render children?.()}
	</div>
{/if}
