// packages/skeleton-react/src/components/qr-code/anatomy/root-context.tsx
import type { ReactNode } from 'react';
import { use } from 'react';
import type { useQrCode } from '../modules/provider.js';
import { QrCodeRootContext as RootContext_ } from '../modules/root-context.js';

export interface QrCodeRootContextProps {
	children: (qrCode: ReturnType<typeof useQrCode>) => ReactNode;
}

export default function QrCodeRootContext(props: QrCodeRootContextProps) {
	const qrCode = use(RootContext_);

	const { children } = props;

	return children(qrCode);
}

// packages/skeleton-svelte/src/components/qr-code/anatomy/root-context.svelte
<script lang="ts" module>
	import type { useQrCode } from '../modules/provider.svelte';
	import type { Snippet } from 'svelte';

	export interface QrCodeRootContextProps {
		children: Snippet<[ReturnType<typeof useQrCode>]>;
	}
</script>

<script lang="ts">
	import { QrCodeRootContext } from '../modules/root-context.js';

	const props: QrCodeRootContextProps = $props();

	const qrCode = QrCodeRootContext.consume();

	const { children } = $derived(props);
</script>

{@render children(qrCode)}
