// sites/next.skeleton.dev/src/examples/components/popover/ExampleModal.tsx
// Tutorial: https://floating-ui.com/docs/dialog

import React, { useState } from 'react';
import {
	useFloating,
	useClick,
	useDismiss,
	useRole,
	useInteractions,
	useId,
	FloatingOverlay,
	FloatingFocusManager,
	useTransitionStyles
} from '@floating-ui/react';

export const Page: React.FC = () => {
	const [isOpen, setIsOpen] = useState(false);

	const { refs, context } = useFloating({
		open: isOpen,
		onOpenChange: setIsOpen
	});

	// https://floating-ui.com/docs/useTransition#usetransitionstatus
	const { isMounted, styles } = useTransitionStyles(context, {
		duration: 200,
		initial: {
			opacity: 0,
			transform: 'translateY(50px)'
		}
	});

	const click = useClick(context);
	const dismiss = useDismiss(context, {
		outsidePressEvent: 'mousedown'
	});
	const role = useRole(context);

	const { getReferenceProps, getFloatingProps } = useInteractions([click, dismiss, role]);

	const labelId = useId();
	const descriptionId = useId();

	return (
		<>
			{/* Trigger */}
			<button ref={refs.setReference} {...getReferenceProps()} className="btn preset-tonal">
				Open Modal
			</button>
			{isMounted && (
				// Backdrop
				<FloatingOverlay
					lockScroll
					className="fixed top-0 left-0 right-0 bottom-0 z-[998] bg-surface-50/75 dark:bg-surface-950/75 backdrop-blur-sm flex justify-center items-center p-4"
				>
					<FloatingFocusManager context={context}>
						{/* Modal */}
						<div
							ref={refs.setFloating}
							aria-labelledby={labelId}
							aria-describedby={descriptionId}
							{...getFloatingProps()}
							className="card bg-surface-100-900 p-4 space-y-4 shadow-xl max-w-screen-sm"
							style={{
								...styles // Transition styles
							}}
						>
							<header className="flex justify-between">
								<h2 className="h2">Modal Example</h2>
							</header>
							<article>
								<p className="opacity-60">
									Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam, ab adipisci. Libero cumque sunt quis error veritatis amet,
									expedita voluptatem. Quos repudiandae consequuntur voluptatem et dicta quas, reprehenderit velit excepturi?
								</p>
							</article>
							<footer className="flex justify-end gap-4">
								<button type="button" className="btn preset-tonal" onClick={() => setIsOpen(false)}>
									Cancel
								</button>
								<button type="button" className="btn preset-filled" onClick={() => setIsOpen(false)}>
									Confirm
								</button>
							</footer>
						</div>
					</FloatingFocusManager>
				</FloatingOverlay>
			)}
		</>
	);
};

// sites/next.skeleton.dev/src/examples/components/popover/ExampleModal.svelte
<script lang="ts">
	import { Modal } from '@skeletonlabs/skeleton-svelte';

	let openState = $state(false);

	function modalClose() {
		openState = false;
	}
</script>

<Modal
	open={openState}
	onOpenChange={(e) => (openState = e.open)}
	triggerBase="btn preset-tonal"
	contentBase="card bg-surface-100-900 p-4 space-y-4 shadow-xl max-w-screen-sm"
	backdropClasses="backdrop-blur-sm"
>
	{#snippet trigger()}Open Modal{/snippet}
	{#snippet content()}
		<header class="flex justify-between">
			<h2 class="h2">Modal Example</h2>
		</header>
		<article>
			<p class="opacity-60">
				Lorem ipsum dolor sit amet consectetur adipisicing elit. Nam, ab adipisci. Libero cumque sunt quis error veritatis amet, expedita
				voluptatem. Quos repudiandae consequuntur voluptatem et dicta quas, reprehenderit velit excepturi?
			</p>
		</article>
		<footer class="flex justify-end gap-4">
			<button type="button" class="btn preset-tonal" onclick={modalClose}>Cancel</button>
			<button type="button" class="btn preset-filled" onclick={modalClose}>Confirm</button>
		</footer>
	{/snippet}
</Modal>
