// sites/skeleton.dev/src/examples/components/toast/ExamplePlacement.tsx
'use client';

import { Toaster, createToaster } from '@skeletonlabs/skeleton-react';

export default function () {
	const toaster = createToaster({
		placement: 'top-end'
	});
	return (
		<>
			<Toaster toaster={toaster}></Toaster>
			<button
				className="btn preset-filled"
				onClick={() => {
					toaster.info({
						title: 'This is a toast!'
					});
				}}
			>
				Toast!
			</button>
		</>
	);
}

// sites/next.skeleton.dev/src/examples/components/popover/ExamplePlacement.svelte
<script lang="ts">
	import { Popover } from '@skeletonlabs/skeleton-svelte';
</script>

<Popover triggerBase="btn preset-filled" positioning={{ placement: 'top' }}>
	{#snippet trigger()}Click Me{/snippet}
	{#snippet content()}
		<div class="card bg-surface-200-800 p-4">
			<p>A simple tooltip.</p>
		</div>
	{/snippet}
</Popover>
