// packages/skeleton-react/src/components/carousel/anatomy/autoplay-trigger.tsx
import type { HTMLAttributes } from '../../../internal/html-attributes.js';
import type { PropsWithElement } from '../../../internal/props-with-element.js';
import { RootContext } from '../modules/root-context.js';
import { mergeProps } from '@zag-js/react';
import { use } from 'react';

export interface CarouselAutoplayTriggerProps extends PropsWithElement<'button'>, HTMLAttributes<'button'> {}

export default function AutoplayTrigger(props: CarouselAutoplayTriggerProps) {
	const carousel = use(RootContext);

	const { element, children, ...rest } = props;

	const attributes = mergeProps(carousel.getAutoplayTriggerProps(), rest);

	return element ? element(attributes) : <button {...attributes}>{children}</button>;
}

// packages/skeleton-svelte/src/components/carousel/anatomy/autoplay-trigger.svelte
<script lang="ts" module>
	import type { HTMLAttributes } from '../../../internal/html-attributes.js';
	import type { PropsWithElement } from '../../../internal/props-with-element.js';

	export interface CarouselAutoplayTriggerProps extends PropsWithElement<'button'>, HTMLAttributes<'button'> {}
</script>

<script lang="ts">
	import { RootContext } from '../modules/root-context.js';
	import { mergeProps } from '@zag-js/svelte';

	const props: CarouselAutoplayTriggerProps = $props();

	const carousel = RootContext.consume();

	const { element, children, ...rest } = $derived(props);

	const attributes = $derived(mergeProps(carousel().getAutoplayTriggerProps(), rest));
</script>

{#if element}
	{@render element(attributes)}
{:else}
	<button {...attributes}>
		{@render children?.()}
	</button>
{/if}
