// sites/skeleton.dev/src/examples/components/accordion/react/columns.tsx
import { Accordion } from '@skeletonlabs/skeleton-react';
import { Club as IconClub, Diamond as IconDiamond, Heart as IconHeart, Spade as IconSpade } from 'lucide-react';

export default function () {
	return (
		<Accordion>
			<Accordion.Item value="item-1">
				<Accordion.Heading>
					<Accordion.Trigger className="grid-cols-[1fr_auto]">
						<span>Club</span>
						<IconClub />
					</Accordion.Trigger>
					<Accordion.Content>Content for Item 1</Accordion.Content>
				</Accordion.Heading>
			</Accordion.Item>
			<hr className="hr" />
			<Accordion.Item value="item-2">
				<Accordion.Heading>
					<Accordion.Trigger className="grid-cols-[1fr_auto]">
						<span>Diamond</span>
						<IconDiamond />
					</Accordion.Trigger>
					<Accordion.Content>Content for Item 2</Accordion.Content>
				</Accordion.Heading>
			</Accordion.Item>
			<hr className="hr" />
			<Accordion.Item value="item-3">
				<Accordion.Heading>
					<Accordion.Trigger className="grid-cols-[1fr_auto]">
						<span>Heart</span>
						<IconHeart />
					</Accordion.Trigger>
					<Accordion.Content>Content for Item 3</Accordion.Content>
				</Accordion.Heading>
			</Accordion.Item>
			<hr className="hr" />
			<Accordion.Item value="item-4">
				<Accordion.Heading>
					<Accordion.Trigger className="grid-cols-[1fr_auto]">
						<span>Spade</span>
						<IconSpade />
					</Accordion.Trigger>
					<Accordion.Content>Content for Item 4</Accordion.Content>
				</Accordion.Heading>
			</Accordion.Item>
		</Accordion>
	);
}

// sites/skeleton.dev/src/examples/components/accordion/svelte/columns.svelte
<script lang="ts">
	import { Accordion } from '@skeletonlabs/skeleton-svelte';
	import IconClub from '@lucide/svelte/icons/club';
	import IconDiamond from '@lucide/svelte/icons/diamond';
	import IconHeart from '@lucide/svelte/icons/heart';
	import IconSpade from '@lucide/svelte/icons/spade';
</script>

<Accordion>
	<Accordion.Item value="club">
		<Accordion.Heading>
			<Accordion.Trigger class="grid-cols-[1fr_auto]">
				<span>Club</span>
				<IconClub />
			</Accordion.Trigger>
			<Accordion.Content>Content for Item 1</Accordion.Content>
		</Accordion.Heading>
	</Accordion.Item>
	<hr class="hr" />
	<Accordion.Item value="diamond">
		<Accordion.Heading>
			<Accordion.Trigger class="grid-cols-[1fr_auto]">
				<span>Diamond</span>
				<IconDiamond />
			</Accordion.Trigger>
			<Accordion.Content>Content for Item 2</Accordion.Content>
		</Accordion.Heading>
	</Accordion.Item>
	<hr class="hr" />
	<Accordion.Item value="heart">
		<Accordion.Heading>
			<Accordion.Trigger class="grid-cols-[1fr_auto]">
				<span>Heart</span>
				<IconHeart />
			</Accordion.Trigger>
			<Accordion.Content>Content for Item 3</Accordion.Content>
		</Accordion.Heading>
	</Accordion.Item>
	<hr class="hr" />
	<Accordion.Item value="spade">
		<Accordion.Heading>
			<Accordion.Trigger class="grid-cols-[1fr_auto]">
				<span>Spade</span>
				<IconSpade />
			</Accordion.Trigger>
			<Accordion.Content>Content for Item 4</Accordion.Content>
		</Accordion.Heading>
	</Accordion.Item>
</Accordion>
