// packages/skeleton-svelte/src/components/carousel/anatomy/indicator-group.svelte
<script lang="ts" module>
	import type { HTMLAttributes } from '../../../internal/html-attributes.js';
	import type { PropsWithElement } from '../../../internal/props-with-element.js';

	export interface CarouselIndicatorGroupProps extends PropsWithElement<'div'>, HTMLAttributes<'div'> {}
</script>

<script lang="ts">
	import { RootContext } from '../modules/root-context.js';
	import { mergeProps } from '@zag-js/svelte';

	const props: CarouselIndicatorGroupProps = $props();

	const carousel = RootContext.consume();

	const { element, children, ...rest } = $derived(props);

	const attributes = $derived(mergeProps(carousel().getIndicatorGroupProps(), rest));
</script>

{#if element}
	{@render element(attributes)}
{:else}
	<div {...attributes}>
		{@render children?.()}
	</div>
{/if}

// packages/skeleton-react/src/components/carousel/anatomy/indicator-group.tsx
import type { HTMLAttributes } from '../../../internal/html-attributes.js';
import type { PropsWithElement } from '../../../internal/props-with-element.js';
import { RootContext } from '../modules/root-context.js';
import { mergeProps } from '@zag-js/react';
import { use } from 'react';

export interface CarouselIndicatorGroupProps extends PropsWithElement<'div'>, HTMLAttributes<'div'> {}

export default function IndicatorGroup(props: CarouselIndicatorGroupProps) {
	const carousel = use(RootContext);

	const { element, children, ...rest } = props;

	const attributes = mergeProps(carousel.getIndicatorGroupProps(), rest);

	return element ? element(attributes) : <div {...attributes}>{children}</div>;
}
