// packages/skeleton-svelte/src/components/carousel/anatomy/item-group.svelte
<script lang="ts" module>
	import type { HTMLAttributes } from '../../../internal/html-attributes.js';
	import type { PropsWithElement } from '../../../internal/props-with-element.js';

	export interface CarouselItemGroupProps extends PropsWithElement<'div'>, HTMLAttributes<'div'> {}
</script>

<script lang="ts">
	import { CarouselRootContext } from '../modules/root-context.js';
	import { mergeProps } from '@zag-js/svelte';

	const props: CarouselItemGroupProps = $props();

	const carousel = CarouselRootContext.consume();

	const { element, children, ...rest } = $derived(props);

	const attributes = $derived(mergeProps(carousel().getItemGroupProps(), rest));
</script>

{#if element}
	{@render element(attributes)}
{:else}
	<div {...attributes}>
		{@render children?.()}
	</div>
{/if}

// packages/skeleton-react/src/components/carousel/anatomy/item-group.tsx
import type { HTMLAttributes } from '../../../internal/html-attributes.js';
import type { PropsWithElement } from '../../../internal/props-with-element.js';
import { CarouselRootContext } from '../modules/root-context.js';
import { mergeProps } from '@zag-js/react';
import { use } from 'react';

export interface CarouselItemGroupProps extends PropsWithElement<'div'>, HTMLAttributes<'div'> {}

export default function ItemGroup(props: CarouselItemGroupProps) {
	const carousel = use(CarouselRootContext);

	const { element, children, ...rest } = props;

	const attributes = mergeProps(carousel.getItemGroupProps(), rest);

	return element ? element(attributes) : <div {...attributes}>{children}</div>;
}
