// packages/skeleton-react/src/components/Avatar/Avatar.tsx
"use client";

import React from "react";
import { AvatarProps, FigureProps } from "./types";

// Components
const Figure: React.FC<FigureProps> = ({
    // Root
    base = '',
    background = '',
    size = '',
    font = '',
    border = '',
    rounded = '',
    shadow = '',
    classes = '',
    // Image
    imageSrc = '',
    imageAlt = '',
    imageFilter = '',
    imageBase = '',
    imageClasses = '',
    // Children
    children
}): React.ReactElement => {
    return(
        <figure className={`${base} ${background} ${size} ${font} ${border} ${rounded} ${shadow} ${classes}`} data-testId="avatar">
            {imageSrc ? (
                <img className={`${imageBase} ${imageClasses}`} src={imageSrc} alt={imageAlt} style={{ filter: `url(${imageFilter})` }} />
            ) : (
                children
            )}
	    </figure>  
    );
};

const Avatar: React.FC<AvatarProps> = ({
    // Root
    base = 'overflow-hidden isolate',
    background = 'bg-surface-400-600',
    size = 'size-16',
    font = '',
    border = '',
    rounded = 'rounded-full',
    shadow = '',
    classes = '',
    // Image
    imageSrc = '',
    imageAlt = '',
    imageFilter = '',
    imageBase = 'w-full object-cover',
    imageClasses = '',
    // Anchor
    anchorHref = '',
    anchorBase = 'inline-block',
    anchorClasses = '',
    // Children
    children
}): React.ReactElement => {
    const figureProps = {
        base,
        background,
        size,
        font,
        border,
        rounded,
        shadow,
        classes,
        imageSrc,
        imageAlt,
        imageFilter,
        imageBase,
        imageClasses,
        children
    }
    return anchorHref ? (
        <a href={anchorHref} className={`${anchorBase} ${anchorClasses}`} data-testId="avatar-anchor">
            <Figure {...figureProps} />
        </a>
    ) : (
        <Figure {...figureProps} />
    )
};

export default Avatar;

// packages/skeleton-svelte/src/lib/components/Avatar/Avatar.svelte
<script lang="ts">
	import type { AvatarProps } from './types.js';

	let {
		// Root
		base = 'overflow-hidden isolate',
		background = 'bg-surface-400-600',
		size = 'size-16',
		font = '',
		border = '',
		rounded = 'rounded-full',
		shadow = '',
		classes = '',
		// Image
		imageSrc = '',
		imageAlt = '',
		imageFilter = '',
		imageBase = 'w-full object-cover',
		imageClasses = '',
		// Anchor
		anchorHref = '',
		anchorBase = 'inline-block',
		anchorClasses = '',
		// Snippets
		children
	} = $props<AvatarProps>();
</script>

{#snippet figure()}
	<figure class="{base} {background} {size} {font} {border} {rounded} {shadow} {classes}" data-testId="avatar">
		{#if imageSrc}
			<img class="{imageBase} {imageClasses}" src={imageSrc} alt={imageAlt} style="filter:url({imageFilter})" />
		{:else if children}
			{@render children()}
		{/if}
	</figure>
{/snippet}

{#if anchorHref}
	<a href={anchorHref} class="{anchorBase} {anchorClasses}" data-testId="avatar-anchor">
		{@render figure()}
	</a>
{:else}
	{@render figure()}
{/if}
