// packages/skeleton-react/src/lib/components/Tabs/Tabs.tsx
'use client';

import { FC, useContext, useId } from 'react';
import * as tabs from '@zag-js/tabs';
import { useMachine, normalizeProps } from '@zag-js/react';
import { TabsRootProps, TabsListProps, TabsControlProps, TabsContentProps, TabsPanelProps } from './types.js';
import { TabsContext } from './contexts.js';
import { noop } from '../../internal/noop.js';

const TabsRoot: FC<TabsRootProps> = ({
	fluid = false,
	// Root
	base = 'w-full',
	classes = '',
	// Events
	onValueChange = noop,
	// Children
	children,
	// Zag
	...zagProps
}) => {
	// Zag
	const [state, send] = useMachine(
		tabs.machine({
			id: useId(),
			onValueChange: (details) => onValueChange(details.value)
		}),
		{ context: zagProps }
	);
	const api = tabs.connect(state, send, normalizeProps);

	return (
		<div {...api.getRootProps()} className={`${base} ${classes}`} data-testid="tabs">
			<TabsContext.Provider value={{ fluid, api }}>{children}</TabsContext.Provider>
		</div>
	);
};

const TabsList: FC<TabsListProps> = ({
	// Root
	base = 'flex',
	justify = 'justify-start',
	border = 'border-b-[1px] border-surface-200-800',
	margin = 'mb-4',
	gap = 'gap-2',
	classes = '',
	// Children
	children
}) => {
	const ctx = useContext(TabsContext);

	return (
		<div {...ctx.api.getListProps()} className={`${base} ${justify} ${border} ${margin} ${gap} ${classes}`} data-testid="tabs-list">
			{children}
		</div>
	);
};

const TabsControl: FC<TabsControlProps> = ({
	// Root
	base = 'border-b-[1px] border-transparent',
	padding = 'pb-2',
	translateX = 'translate-y-[1px]',
	classes = '',
	// Label
	labelBase = 'btn hover:preset-tonal-primary',
	labelClasses = '',
	// State
	stateInactive = '[&:not(:hover)]:opacity-50',
	stateActive = 'border-surface-950-50 opacity-100',
	stateLabelInactive = '',
	stateLabelActive = '',
	// Nodes
	lead,
	// Children
	children,
	// Zag
	...zagProps
}) => {
	const ctx = useContext(TabsContext);
	const state = ctx.api.getTriggerState(zagProps);

	// Reactive
	const rxActive = state.selected ? stateActive : stateInactive;
	const rxLabelActive = state.selected ? stateLabelActive : stateLabelInactive;

	// Styles
	const commonStyles = { width: ctx.fluid ? '100%' : '' };

	return (
		<button
			{...ctx.api.getTriggerProps(zagProps)}
			className={`${base} ${padding} ${translateX} ${rxActive} ${classes}`}
			style={commonStyles}
			data-testid="tabs-control"
		>
			{/* Label */}
			<div className={`${labelBase} ${rxLabelActive} ${labelClasses}`} style={commonStyles} data-testid="tabs-control-label">
				{lead && <span data-testid="tabs-control-lead">{lead}</span>}
				<span data-testid="tabs-control-children">{children}</span>
			</div>
		</button>
	);
};

const TabsContent: FC<TabsContentProps> = ({
	// Root
	base = '',
	classes = '',
	// Children
	children
}) => {
	return (
		<div className={`${base} ${classes}`} data-testid="tabs-content">
			{children}
		</div>
	);
};

const TabsPanel: FC<TabsPanelProps> = ({
	// Root
	base = '',
	classes = '',
	// Children
	children,
	// Zag
	...zagProps
}) => {
	const ctx = useContext(TabsContext);

	return (
		<div {...ctx.api.getContentProps(zagProps)} className={`${base} ${classes}`} data-testid="tabs-panel">
			{children}
		</div>
	);
};

// Export ---

export const Tabs = Object.assign(TabsRoot, {
	/** A group of tab controls. */
	List: TabsList,
	/** An individual tab control. */
	Control: TabsControl,
	/** A group of tab panels. */
	Content: TabsContent,
	/** An individual tab panel. */
	Panel: TabsPanel
});

// packages/skeleton-svelte/src/lib/components/Tabs/Tabs.svelte
<script lang="ts">
	import * as tabs from '@zag-js/tabs';
	import { useMachine, normalizeProps } from '@zag-js/svelte';
	import type { TabsProps } from './types.js';
	import { setTabContext } from './context.js';
	import { useId } from '$lib/internal/use-id.js';

	let {
		value = $bindable(''),
		fluid = false,
		// Root
		base = 'w-full',
		classes = '',
		// List
		listBase = 'flex',
		listJustify = 'justify-start',
		listBorder = 'border-b-[1px] border-surface-200-800',
		listMargin = 'mb-4',
		listGap = 'gap-2',
		listClasses = '',
		// Content
		contentBase = '',
		contentClasses = '',
		// Snippets
		list,
		content,
		// Zag
		...zagProps
	}: TabsProps = $props();

	// Zag
	const [snapshot, send] = useMachine(
		tabs.machine({
			id: useId(),
			onValueChange(details) {
				value = details.value;
			}
		}),
		{
			context: {
				...zagProps,
				get value() {
					return value;
				}
			}
		}
	);
	const api = $derived(tabs.connect(snapshot, send, normalizeProps));

	// Set Context
	setTabContext({
		get api() {
			return api;
		},
		get fluid() {
			return fluid;
		}
	});
</script>

<!-- @component Use tabs to quickly switch between different views and pages. -->

<div {...api.getRootProps()} class="{base} {classes}" data-testid="tabs">
	<!-- List -->
	<div {...api.getListProps()} class="{listBase} {listJustify} {listBorder} {listMargin} {listGap} {listClasses}" data-testid="tabs-list">
		{@render list?.()}
	</div>
	<!-- Content -->
	<div class="{contentBase} {contentClasses}" data-testid="tabs-content">
		{@render content?.()}
	</div>
</div>
