// packages/skeleton-svelte/src/components/progress-linear/anatomy/root.svelte
<script lang="ts" module>
	import type { HTMLAttributes } from '@/internal/html-attributes';
	import type { PropsWithElement } from '@/internal/props-with-element';
	import type { Props } from '@zag-js/progress';

	export interface ProgressLinearRootProps extends Omit<Props, 'id'>, PropsWithElement<'div'>, HTMLAttributes<'div', 'id' | 'dir'> {}
</script>

<script lang="ts">
	import { useProgressLinear } from '../modules/provider.svelte';
	import { RootContext } from '../modules/root-context';
	import { classesProgressLinear } from '@skeletonlabs/skeleton-common';
	import { splitProps } from '@zag-js/progress';
	import { mergeProps } from '@zag-js/svelte';

	const props: ProgressLinearRootProps = $props();

	const [progressLinearProps, componentProps] = $derived(splitProps(props));
	const { element, children, ...rest } = $derived(componentProps);

	const id = $props.id();
	const avatar = useProgressLinear(() => ({
		id,
		...progressLinearProps,
	}));

	const attributes = $derived(
		mergeProps(
			avatar().getRootProps(),
			{
				class: classesProgressLinear.root,
			},
			rest,
		),
	);

	RootContext.provide(() => avatar());
</script>

{#if element}
	{@render element(attributes)}
{:else}
	<div {...attributes}>
		{@render children?.()}
	</div>
{/if}

// packages/skeleton-react/src/components/progress-linear/anatomy/root.tsx
import { useProgressLinear } from '../modules/provider';
import { RootContext } from '../modules/root-context';
import type { HTMLAttributes } from '@/internal/html-attributes';
import type { PropsWithElement } from '@/internal/props-with-element';
import { classesProgressLinear } from '@skeletonlabs/skeleton-common';
import { splitProps } from '@zag-js/progress';
import type { Props } from '@zag-js/progress';
import { mergeProps } from '@zag-js/react';

export interface ProgressLinearRootProps
	extends Omit<Props, 'id'>,
		PropsWithElement<'div'>,
		HTMLAttributes<'div', 'id' | 'dir' | 'defaultValue'> {}

export default function Root(props: ProgressLinearRootProps) {
	const [progressLinearProps, componentProps] = splitProps(props);
	const { element, children, ...rest } = componentProps;

	const progressLinear = useProgressLinear(progressLinearProps);

	const attributes = mergeProps(
		progressLinear.getRootProps(),
		{
			className: classesProgressLinear.root,
		},
		rest,
	);

	return (
		<RootContext.Provider value={progressLinear}>
			{element ? element(attributes) : <div {...attributes}>{children}</div>}
		</RootContext.Provider>
	);
}
