// packages/skeleton-svelte/src/components/avatar/anatomy/fallback.svelte
<script lang="ts" module>
	import type { HTMLAttributes } from '@/internal/html-attributes';
	import type { PropsWithElement } from '@/internal/props-with-element';

	export interface AvatarFallbackProps extends PropsWithElement<'span'>, HTMLAttributes<'span'> {}
</script>

<script lang="ts">
	import { RootContext } from '../modules/root-context';
	import { classesAvatar } from '@skeletonlabs/skeleton-common';
	import { mergeProps } from '@zag-js/svelte';

	const props: AvatarFallbackProps = $props();

	const avatar = RootContext.consume();

	const { element, children, ...rest } = $derived(props);

	const attributes = $derived(
		mergeProps(
			avatar().getFallbackProps(),
			{
				class: classesAvatar.fallback,
			},
			rest,
		),
	);
</script>

{#if element}
	{@render element(attributes)}
{:else}
	<span {...attributes}>
		{@render children?.()}
	</span>
{/if}

// packages/skeleton-react/src/components/avatar/anatomy/fallback.tsx
import { RootContext } from '../modules/root-context';
import type { HTMLAttributes } from '@/internal/html-attributes';
import type { PropsWithElement } from '@/internal/props-with-element';
import { classesAvatar } from '@skeletonlabs/skeleton-common';
import { mergeProps } from '@zag-js/react';
import { use } from 'react';

export interface AvatarFallbackProps extends PropsWithElement<'span'>, HTMLAttributes<'span'> {}

export default function Fallback(props: AvatarFallbackProps) {
	const avatar = use(RootContext);

	const { element, children, ...rest } = props;

	const attributes = mergeProps(
		avatar.getFallbackProps(),
		{
			className: classesAvatar.fallback,
		},
		rest,
	);

	return element ? element(attributes) : <span {...attributes}>{children}</span>;
}
