// packages/skeleton-svelte/src/components/avatar/anatomy/root-provider.svelte
<script lang="ts" module>
	import type { useAvatar } from '../modules/use-avatar.svelte';
	import type { HTMLAttributes } from '@/internal/html-attributes';
	import type { PropsWithElement } from '@/internal/props-with-element';

	export interface AvatarRootProviderProps extends PropsWithElement<'div'>, HTMLAttributes<'div', 'id' | 'dir'> {
		value: ReturnType<typeof useAvatar>;
	}
</script>

<script lang="ts">
	import { AvatarRootContext } from '../modules/root-context';
	import { classesAvatar } from '@skeletonlabs/skeleton-common';
	import { mergeProps } from '@zag-js/svelte';

	const props: AvatarRootProviderProps = $props();

	const { element, children, value: avatar, ...rest } = $derived(props);

	const attributes = $derived(
		mergeProps(avatar().getRootProps(), rest, {
			class: classesAvatar.root,
		}),
	);

	AvatarRootContext.provide(() => avatar());
</script>

{#if element}
	{@render element(attributes)}
{:else}
	<div {...attributes}>
		{@render children?.()}
	</div>
{/if}

// packages/skeleton-react/src/components/avatar/anatomy/root-provider.tsx
import { mergeProps } from '@zag-js/react';
import { classesAvatar } from '@skeletonlabs/skeleton-common';
import { AvatarRootContext } from '../modules/root-context';
import type { PropsWithElement } from '@/internal/props-with-element';
import type { HTMLAttributes } from '@/internal/html-attributes';
import type { useAvatar } from '../modules/use-avatar';

export interface AvatarRootProviderProps extends PropsWithElement<'div'>, HTMLAttributes<'div', 'id' | 'dir'> {
	value: ReturnType<typeof useAvatar>;
}

export default function (props: AvatarRootProviderProps) {
	const { element, children, value: avatar, ...rest } = props;

	const attributes = mergeProps(avatar.getRootProps(), rest, {
		className: classesAvatar.root
	});

	return (
		<AvatarRootContext.Provider value={avatar}>
			{element ? element(attributes) : <div {...attributes}>{children}</div>}
		</AvatarRootContext.Provider>
	);
}
