// sites/next.skeleton.dev/src/examples/components/ratings/StepExample.tsx
import React, { useState } from 'react';
import { Rating } from '@skeletonlabs/skeleton-react';
import { Star } from 'lucide-react';

export const Page: React.FC = () => {
	const [value, setValue] = useState(2.5);
	return (
		<Rating
			value={value}
			onValueChange={setValue}
			step={2}
			width="w-44"
			interactive
			iconEmpty={<Star size={24} />}
			iconFull={<Star size={24} className="fill-surface-950-50" />}
		/>
	);
};

// sites/next.skeleton.dev/src/examples/components/ratings/StepExample.svelte
<script lang="ts">
	import { Rating } from '@skeletonlabs/skeleton-svelte';
	import Star from 'lucide-svelte/icons/star';
</script>

<Rating value={2.5} step={2} width="w-44" interactive>
	{#snippet iconFull()}
		<Star size={24} class="fill-surface-950-50" />
	{/snippet}
	{#snippet iconEmpty()}
		<Star size={24} />
	{/snippet}
</Rating>
