// sites/next.skeleton.dev/src/examples/components/navigation/ExampleExpanded.tsx
import { Navigation } from '@skeletonlabs/skeleton-react';
import {
	Menu as IconMenu,
	Folder as IconFolder,
	Image as IconImage,
	Music as IconMusic,
	Video as IconVideo,
	Gamepad as IconGames,
	Settings as IconSettings
} from 'lucide-react';

export const Page: React.FC = () => {
	return (
		<div className="card border-surface-100-900 grid h-[640px] w-full grid-cols-[auto_1fr] border-[1px]">
			{/* Component */}
			<Navigation.Rail
				expanded
				header={
					<Navigation.Tile href="/" labelExpanded="Menu">
						<IconMenu />
					</Navigation.Tile>
				}
				footer={
					<Navigation.Tile href="/settings" labelExpanded="Settings">
						<IconSettings />
					</Navigation.Tile>
				}
			>
				<Navigation.Tile id="0" labelExpanded="Browse Files" href="#">
					<IconFolder />
				</Navigation.Tile>
				<Navigation.Tile id="1" labelExpanded="Browse Images" href="#">
					<IconImage />
				</Navigation.Tile>
				<Navigation.Tile id="2" labelExpanded="Browse Music" href="#">
					<IconMusic />
				</Navigation.Tile>
				<Navigation.Tile id="3" labelExpanded="Browse Videos" href="#">
					<IconVideo />
				</Navigation.Tile>
				<Navigation.Tile id="4" labelExpanded="Browse Games" href="#">
					<IconGames />
				</Navigation.Tile>
			</Navigation.Rail>
			{/* Content */}
			<div className="flex items-center justify-center">
				<p className="opacity-20">(Content)</p>
			</div>
		</div>
	);
};

// sites/next.skeleton.dev/src/examples/components/navigation/ExampleExpanded.svelte
<script lang="ts">
	import { Navigation } from '@skeletonlabs/skeleton-svelte';
	// Icons
	import IconMenu from 'lucide-svelte/icons/menu';
	import IconFolder from 'lucide-svelte/icons/folder';
	import IconImage from 'lucide-svelte/icons/image';
	import IconMusic from 'lucide-svelte/icons/music';
	import IconVideo from 'lucide-svelte/icons/video';
	import IconGames from 'lucide-svelte/icons/gamepad';
	import IconSettings from 'lucide-svelte/icons/settings';

	let hrefExample = '#';
</script>

<div class="card border-surface-100-900 grid h-[760px] w-full grid-cols-[auto_1fr] border-[1px]">
	<!-- Component -->
	<Navigation.Rail expanded>
		{#snippet header()}
			<Navigation.Tile href="/" labelExpanded="Menu"><IconMenu /></Navigation.Tile>
		{/snippet}
		{#snippet tiles()}
			<Navigation.Tile id="0" labelExpanded="Browse Files" href={hrefExample}>
				<IconFolder />
			</Navigation.Tile>
			<Navigation.Tile id="1" labelExpanded="Browse Images" href={hrefExample}>
				<IconImage />
			</Navigation.Tile>
			<Navigation.Tile id="2" labelExpanded="Browse Music" href={hrefExample}>
				<IconMusic />
			</Navigation.Tile>
			<Navigation.Tile id="2" labelExpanded="Browse Videos" href={hrefExample}>
				<IconVideo />
			</Navigation.Tile>
			<Navigation.Tile id="2" labelExpanded="Browse Games" href={hrefExample}>
				<IconGames />
			</Navigation.Tile>
		{/snippet}
		{#snippet footer()}
			<Navigation.Tile labelExpanded="Settings" href="/settings" title="Settings"><IconSettings /></Navigation.Tile>
		{/snippet}
	</Navigation.Rail>
	<!-- Content -->
	<div class="flex items-center justify-center">
		<p class="opacity-20">(Content)</p>
	</div>
</div>
