// packages/skeleton-react/src/components/rating-group/anatomy/rating-group-label.tsx
import { useContext } from 'react';
import { RatingGroupRootContext } from '../modules/context.js';
import type { RatingGroupLabelProps } from '../modules/types.js';
import { mergeProps } from '@zag-js/react';
import { classesRatingGroup } from '@skeletonlabs/skeleton-common';

export default function (props: RatingGroupLabelProps) {
	const rootContext = useContext(RatingGroupRootContext);
	const { element, children, ...restAttributes } = props;
	const attributes = mergeProps(
		rootContext.api.getLabelProps(),
		{
			className: classesRatingGroup.label
		},
		restAttributes
	);
	return element ? element({ attributes }) : <label {...attributes}>{children}</label>;
}

// packages/skeleton-svelte/src/components/rating-group/anatomy/rating-group-label.svelte
<script lang="ts">
	import { mergeProps } from '@zag-js/svelte';
	import { RatingGroupRootContext } from '../modules/context.js';
	import { classesRatingGroup } from '@skeletonlabs/skeleton-common';
	import type { RatingGroupLabelProps } from '../modules/types.js';

	const rootContext = RatingGroupRootContext.consume();
	const props: RatingGroupLabelProps = $props();
	const { element, children, ...restAttributes } = $derived(props);
	const attributes = $derived(
		mergeProps(
			rootContext.api.getControlProps(),
			{
				class: classesRatingGroup.label
			},
			restAttributes
		)
	);
</script>

{#if element}
	{@render element({ attributes })}
{:else}
	<label {...attributes}>{@render children?.()}</label>
{/if}
