// packages/skeleton-react/src/components/rating-group/anatomy/root-context.tsx
import { RatingGroupRootContext } from '../modules/root-context';
import type { useRatingGroup } from '../modules/use-rating-group';
import { use } from 'react';
import type { ReactNode } from 'react';

export interface RatingGroupRootContextProps {
	children: (ratingGroup: ReturnType<typeof useRatingGroup>) => ReactNode;
}

export default function RootContext(props: RatingGroupRootContextProps) {
	const ratingGroup = use(RatingGroupRootContext);

	const { children } = props;

	return children(ratingGroup);
}

// packages/skeleton-svelte/src/components/rating-group/anatomy/root-context.svelte
<script lang="ts" module>
	import type { Snippet } from 'svelte';

	import type { useRatingGroup } from '../modules/use-rating-group.svelte';

	export interface RatingGroupRootContextProps {
		children: Snippet<[ReturnType<typeof useRatingGroup>]>;
	}
</script>

<script lang="ts">
	import { RatingGroupRootContext } from '../modules/root-context';

	const props: RatingGroupRootContextProps = $props();

	const ratingGroup = RatingGroupRootContext.consume();

	const { children } = $derived(props);
</script>

{@render children(ratingGroup)}
