// sites/next.skeleton.dev/src/examples/components/app-bars/ExampleToolbar.svelte
<script lang="ts">
	import { AppBar } from '@skeletonlabs/skeleton-svelte';
	import ArrowLeft from 'lucide-svelte/icons/arrow-left';
	import Paperclip from 'lucide-svelte/icons/paperclip';
	import Calendar from 'lucide-svelte/icons/calendar';
	import CircleUser from 'lucide-svelte/icons/circle-user';
</script>

<AppBar>
	{#snippet lead()}
		<ArrowLeft size={24} />
	{/snippet}
	{#snippet trail()}
		<Paperclip size={20} />
		<Calendar size={20} />
		<CircleUser size={20} />
	{/snippet}
	<span>Title</span>
</AppBar>

// sites/next.skeleton.dev/src/examples/components/app-bars/ExampleToolbar.tsx
import React from 'react';
import { AppBar, ToolBar } from '@skeletonlabs/skeleton-react';
import { ArrowLeft, Paperclip, Calendar, CircleUser } from 'lucide-react';

export const Page: React.FC<any> = () => {
	return (
		<AppBar>
			<AppBar.Toolbar>
				<ToolBar.Lead>
					<ArrowLeft size={24} />
				</ToolBar.Lead>
				<ToolBar.Center>Title</ToolBar.Center>
				<ToolBar.Trail>
					<Paperclip size={20} />
					<Calendar size={20} />
					<CircleUser size={20} />
				</ToolBar.Trail>
			</AppBar.Toolbar>
		</AppBar>
	);
};
