// sites/next.skeleton.dev/src/examples/components/app-bars/ResponsiveExample.svelte
<script lang="ts">
    import { AppBar } from '@skeletonlabs/skeleton-svelte';
    import ArrowLeft from 'lucide-svelte/icons/arrow-left';
    import Paperclip from 'lucide-svelte/icons/paperclip';
    import Calendar from 'lucide-svelte/icons/calendar';
    import CircleUser from 'lucide-svelte/icons/circle-user';
    import Menu from 'lucide-svelte/icons/menu';

    // FIXME: required for Astro bug
    let {} = $props<any>()
</script>

<AppBar headlineClasses="sm:hidden">
	{#snippet lead()}
        <ArrowLeft size={24} />
	{/snippet}
    <span class="hidden sm:block">Title</span>
    {#snippet trail()}
        <div class="hidden sm:flex space-x-4">
            <Paperclip size={20} />
            <Calendar size={20} />
            <CircleUser size={20} />
        </div>
        <div class="block sm:hidden">
            <Menu size={20} />
        </div>
    {/snippet}
	{#snippet headline()}
        <h2 class="h2">Title</h2>
    {/snippet}
</AppBar>

// sites/next.skeleton.dev/src/examples/components/app-bars/ResponsiveExample.tsx
import React from 'react';
import { AppBar, ToolBar } from '@skeletonlabs/skeleton-react';
import { ArrowLeft, Paperclip, Calendar, CircleUser, Menu } from 'lucide-react';

export const Page: React.FC<any> = () => {
	return (
		<AppBar>
			<AppBar.Toolbar>
				<ToolBar.Lead>
					<ArrowLeft size={24} />
				</ToolBar.Lead>
				<ToolBar.Center>
					<span className="hidden sm:block">Title</span>
				</ToolBar.Center>
				<ToolBar.Trail>
					<div className="hidden sm:flex space-x-4">
						<Paperclip size={20} />
						<Calendar size={20} />
						<CircleUser size={20} />
					</div>
					<div className="block sm:hidden">
						<Menu size={20} />
					</div>
				</ToolBar.Trail>
			</AppBar.Toolbar>
			<AppBar.Headline classes="sm:hidden">
				<h2 className="h2">Title</h2>
			</AppBar.Headline>
		</AppBar>
	);
};
