// packages/skeleton-react/src/components/tooltip/anatomy/tooltip-arrow.tsx
import { useContext, type ComponentProps } from 'react';
import { mergeProps } from '@zag-js/react';
import { TooltipRootContext } from '../modules/tooltip-root-context';
import { classesTooltip } from '@skeletonlabs/skeleton-common';
import type { PropsWithElement } from '@/internal/props-with-element';

export interface TooltipArrowProps extends PropsWithElement, ComponentProps<'div'> {}

export default function (props: TooltipArrowProps) {
	const rootContext = useContext(TooltipRootContext);
	const { element, children, ...restAttributes } = props;
	const attributes = mergeProps(
		rootContext.api.getArrowProps(),
		{
			style: {
				'--arrow-size': 'calc(var(--spacing) * 2)',
				'--arrow-background': 'var(--color-surface-100-900)'
			},
			className: classesTooltip.arrow
		},
		restAttributes
	);
	return element ? element({ attributes }) : <div {...attributes}>{children}</div>;
}

// packages/skeleton-svelte/src/components/tooltip/anatomy/tooltip-arrow.svelte
<script lang="ts" module>
	import type { PropsWithElement } from '@/internal/props-with-element';
	import type { HTMLAttributes } from 'svelte/elements';

	export interface TooltipArrowProps extends PropsWithElement, HTMLAttributes<HTMLDivElement> {}
</script>

<script lang="ts">
	import { mergeProps } from '@zag-js/svelte';
	import { classesTooltip } from '@skeletonlabs/skeleton-common';
	import { TooltipRootContext } from '../modules/tooltip-root-context';

	const rootContext = TooltipRootContext.consume();
	const props: TooltipArrowProps = $props();
	const { element, children, ...restAttributes } = $derived(props);
	const attributes = $derived(
		mergeProps(
			rootContext.api.getArrowProps(),
			{
				style: '--arrow-size: calc(var(--spacing) * 2); --arrow-background: var(--color-surface-100-900);',
				class: classesTooltip.arrow
			},
			restAttributes
		)
	);
</script>

{#if element}
	{@render element({ attributes })}
{:else}
	<div {...attributes}>
		{@render children?.()}
	</div>
{/if}
