// packages/skeleton-react/src/composed/accordion/anatomy/accordion-heading.tsx
import type { JSX } from 'react';
import { mergeProps } from '@zag-js/react';
import { classesAccordion } from '@skeletonlabs/skeleton-common';
import type { AccordionHeadingProps } from '../modules/types.js';

export default function (props: AccordionHeadingProps) {
	const { level = 3, element, children, ...restAttributes } = props;
	const Tag: keyof JSX.IntrinsicElements = `h${level}`;
	const attributes = mergeProps(
		{
			className: classesAccordion.heading
		},
		restAttributes
	);
	return element ? element({ attributes }) : <Tag {...attributes}>{children}</Tag>;
}

// packages/skeleton-svelte/src/components/accordion/anatomy/accordion-heading.svelte
<script lang="ts">
	import { mergeProps } from '@zag-js/svelte';
	import { classesAccordion } from '@skeletonlabs/skeleton-common';
	import type { AccordionHeadingProps } from '../modules/types.js';

	const props: AccordionHeadingProps = $props();
	const { level = 3, element, children, ...restAttributes } = $derived(props);
	const attributes = $derived(
		mergeProps(
			{
				class: classesAccordion.heading
			},
			restAttributes
		)
	);
	const tag = $derived(`h${level}`);
</script>

{#if element}
	{@render element({ attributes })}
{:else}
	<svelte:element this={tag} {...attributes}>
		{@render children?.()}
	</svelte:element>
{/if}
