// packages/skeleton-react/src/components/combobox/anatomy/root-context.tsx
import type { useCombobox } from '../modules/provider';
import { RootContext as RootContext_ } from '../modules/root-context';
import { type ReactNode, use } from 'react';

export interface ComboboxRootContextProps {
	children: (combobox: ReturnType<typeof useCombobox>) => ReactNode;
}

export default function RootContext(props: ComboboxRootContextProps) {
	const combobox = use(RootContext_);

	const { children } = props;

	return children(combobox);
}

// packages/skeleton-svelte/src/components/collapsible/anatomy/root-context.svelte
<script lang="ts" module>
	import type { useCollapsible } from '../modules/provider.svelte';
	import type { Snippet } from 'svelte';

	export interface CollapsibleRootContextProps {
		children: Snippet<[ReturnType<typeof useCollapsible>]>;
	}
</script>

<script lang="ts">
	import { RootContext } from '../modules/root-context.js';

	const props: CollapsibleRootContextProps = $props();

	const collapsible = RootContext.consume();

	const { children } = $derived(props);
</script>

{@render children(collapsible)}
