// playgrounds/skeleton-svelte/src/routes/components/dialog/+page.svelte
<script lang="ts">
	import { Dialog } from '@skeletonlabs/skeleton-svelte';
</script>

<Dialog>
	<Dialog.Trigger>Open Dialog</Dialog.Trigger>
	<Dialog.Backdrop />
	<Dialog.Positioner>
		<Dialog.Content>
			<Dialog.Title>This is the title</Dialog.Title>
			<Dialog.Description>This is the description</Dialog.Description>
			<Dialog.CloseTrigger>Close</Dialog.CloseTrigger>
		</Dialog.Content>
	</Dialog.Positioner>
</Dialog>

// playgrounds/skeleton-react/src/app/components/dialog/page.tsx
'use client';

import { Dialog } from '@skeletonlabs/skeleton-react';

export default function () {
	return (
		<Dialog>
			<Dialog.Trigger>Open Dialog</Dialog.Trigger>
			<Dialog.Backdrop />
			<Dialog.Positioner>
				<Dialog.Content>
					<Dialog.Title>Dialog Title</Dialog.Title>
					<Dialog.Description>This is a description of the dialog.</Dialog.Description>
					<Dialog.CloseTrigger>Close</Dialog.CloseTrigger>
				</Dialog.Content>
			</Dialog.Positioner>
		</Dialog>
	);
}
