// packages/skeleton-svelte/src/components/avatar/avatar-image.svelte
<script lang="ts" module>
	import type { PropsWithElement } from '../../internal/props-with-element.js';
	import type { HTMLImgAttributes } from 'svelte/elements';

	interface AvatarImageProps extends PropsWithElement, HTMLImgAttributes {}

	export type { AvatarImageProps };
</script>

<script lang="ts">
	import { mergeProps } from '@zag-js/svelte';
	import { classesAvatar } from '@skeletonlabs/skeleton-common';
	import { AvatarRootContext } from './avatar-root-context.js';

	const rootContext = AvatarRootContext.consume();
	const props: AvatarImageProps = $props();
	const { element, ...restAttributes } = $derived(props);
	const attributes = $derived(
		mergeProps(
			rootContext.api.getImageProps(),
			{
				class: classesAvatar.image
			},
			restAttributes
		)
	);
</script>

{#if element}
	{@render element({ attributes })}
{:else}
	<img {...attributes} />
{/if}

// packages/skeleton-react/src/components/avatar/avatar-image.tsx
'use client';

import { useContext, type ComponentProps } from 'react';
import { mergeProps } from '@zag-js/react';
import { AvatarRootContext } from './avatar-root.context';
import { classesAvatar } from '@skeletonlabs/skeleton-common';
import type { PropsWithElement } from '../../internal/props-with-element';

export interface AvatarImageProps extends PropsWithElement, ComponentProps<'img'> {}

export default function (props: AvatarImageProps) {
	const rootContext = useContext(AvatarRootContext);
	const { element, ...restAttributes } = props;
	const attributes = mergeProps(
		rootContext.api.getImageProps(),
		{
			className: classesAvatar.image
		},
		restAttributes
	);
	return element ? element({ attributes }) : <img {...attributes} />;
}
