// packages/skeleton-react/src/components/popover/anatomy/root-context.tsx
import { useContext, type ReactNode } from 'react';
import { PopoverRootContext } from '../modules/root-context';
import type { usePopover } from '../modules/use-popover';

export interface PopoverRootContextProps {
	children: (popover: ReturnType<typeof usePopover>) => ReactNode;
}

export default function (props: PopoverRootContextProps) {
	const popover = useContext(PopoverRootContext);

	const { children } = props;

	return children(popover);
}

// packages/skeleton-svelte/src/components/popover/anatomy/root-context.svelte
<script lang="ts" module>
	import type { Snippet } from 'svelte';

	import type { usePopover } from '../modules/use-popover.svelte';

	export interface PopoverRootContextProps {
		children: Snippet<[ReturnType<typeof usePopover>]>;
	}
</script>

<script lang="ts">
	import { PopoverRootContext } from '../modules/root-context';

	const props: PopoverRootContextProps = $props();

	const popover = PopoverRootContext.consume();

	const { children } = $derived(props);
</script>

{@render children(popover)}
